### ISSUE TITLE
zmq.ZError$IOException: java.nio.channels.ClosedByInterruptException

### ISSUE THREAD

**Issue by manishag** [zeromq/jeromq#190]
Hi,

I am hitting zmq.ZError$IOException: java.nio.channels.ClosedByInterruptException exception in my prod environment. I am not sure how to handle this exception gracefully or why I am hitting this. Here is the stack trace for it

zmq.ZError$IOException: java.nio.channels.ClosedByInterruptException
at zmq.Signaler.send(Signaler.java:108)
at zmq.Mailbox.send(Mailbox.java:83)
at zmq.Ctx.send_command(Ctx.java:356)
at zmq.ZObject.send_command(ZObject.java:364)
at zmq.ZObject.send_own(ZObject.java:180)
at zmq.Own.launch_child(Own.java:128)
at zmq.SocketBase.add_endpoint(SocketBase.java:528)
at zmq.SocketBase.connect(SocketBase.java:519)
at org.zeromq.ZMQ$Socket.connect(ZMQ.java:1156)

Any help on how to handle it is appreciated.

Thanks,
Manish

**Comment by daveyarwood** [comment]
I think this issue is resolved -- see #283.
