### ISSUE TITLE
java.lang.IndexOutOfBoundsException: Index: 1, Size: 1

### ISSUE THREAD

**Issue by lpasquinelli** [zeromq/jeromq#255]
Hi,

i develop an akka java MT application where I'm using zmq to send information across multiple subscribers.
I create multiple Runnable classes and I instantiate ZMQSocket inside of theme.
I found the following exception in my application log, and my application stop to send messages...

java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
        at java.util.ArrayList.rangeCheck(ArrayList.java:635)
        at java.util.ArrayList.get(ArrayList.java:411)
        at zmq.Utils.swap(Utils.java:107)
        at zmq.Dist.write(Dist.java:187)
        at zmq.Dist.distribute(Dist.java:171)
        at zmq.Dist.send_to_matching(Dist.java:151)
        at zmq.XPub.xsend(XPub.java:191)
        at zmq.SocketBase.send(SocketBase.java:613)
        at org.zeromq.ZMQ$Socket.send(ZMQ.java:1206)
        at org.zeromq.ZMQ$Socket.send(ZMQ.java:1197)

**Comment by miniway** [comment]
do you have any test case that I could reproduce? And please make sure ZMQSockets are not shared by multiple threads.

**Comment by lpasquinelli** [comment]
You're right, after an investigation I discover that we implemented a mechanism where ZMQSocket was shared between akka threads... I'm sorry. we can close this bug.
