### ISSUE TITLE
Exception in thread "iothread-2" java.lang.IllegalStateException: BOTTOM

### ISSUE THREAD

**Issue by CGavrila** [zeromq/jeromq#261]
This is probably somewhat related to zeromq/jeromq#209.

I have the following code, which is copied from a tutorial found online:
```
import org.zeromq.ZMQ;

public class Test {

    public static void main(String[] args) {
        ZMQ.Context context = ZMQ.context(1);

        // Socket to talk to server
        System.out.println("Connecting to hello world server");

        ZMQ.Socket socket = context.socket(ZMQ.REQ);
        socket.connect("tcp://localhost:3000");

        for(int requestNbr = 0; requestNbr != 10; requestNbr++) {
            String request = "Hello" ;
            System.out.println("Sending Hello " + requestNbr );
            socket.send(request.getBytes(), 0);

            byte[] reply = socket.recv(0);
            System.out.println("Received " + new String (reply) + " " + requestNbr);
        }

        socket.close();
        context.term();
    }
}
```

As far as I can tell, the exception comes from `byte[] reply = socket.recv(0);`.

Full trace:
```
Exception in thread "iothread-2" java.lang.IllegalStateException: BOTTOM
	at zmq.Req$ReqSession.push_msg(Req.java:187)
	at zmq.V1Decoder.message_ready(V1Decoder.java:139)
	at zmq.V1Decoder.next(V1Decoder.java:49)
	at zmq.DecoderBase.process_buffer(DecoderBase.java:124)
	at zmq.StreamEngine.in_event(StreamEngine.java:307)
	at zmq.IOObject.in_event(IOObject.java:101)
	at zmq.Poller.run(Poller.java:237)
	at java.lang.Thread.run(Thread.java:745)
```

Not really sure what I should do given that this is just a hello world and there aren't too many resources online that I can find.

**Comment by trevorbernard** [comment]
You'll need to use the latest 0.3.5-SNAPSHOT and it should not throw that error anymore.

**Comment by CGavrila** [comment]
Got it. I'll try it and get back to you here if it doesn't work. Thanks!

**Comment by CGavrila** [comment]
I still get the same thing with `0.3.5-SNAPSHOT`:

```
Exception in thread "iothread-2" java.lang.IllegalStateException: BOTTOM
	at zmq.Req$ReqSession.push_msg(Req.java:184)
	at zmq.V1Decoder.message_ready(V1Decoder.java:158)
	at zmq.V1Decoder.next(V1Decoder.java:68)
	at zmq.DecoderBase.process_buffer(DecoderBase.java:122)
	at zmq.StreamEngine.in_event(StreamEngine.java:306)
	at zmq.IOObject.in_event(IOObject.java:99)
	at zmq.Poller.run(Poller.java:236)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by brimzi** [comment]
I tried running your code with 0.3.5-SNAPSHOT but I do not get any error.What environment are you running the code in?

**Comment by CGavrila** [comment]
My OS is Ubuntu 14.04 (I guess it shouldn't matter, though) and I was using Java 8. Anything else which might be useful?

I have since deleted the code, but I might be able to reproduce it if I retry it.

**Comment by trevorbernard** [comment]
Have you tried using the latest master? That error should not be possible anymore. It is quite possible that the 0.3.5-SNAPSHOT doesn't contain the fix
