### ISSUE TITLE
TestZActor unit test hangs

### ISSUE THREAD

**Issue by sbanacho** [zeromq/jeromq#275]
I get occasional hanging unit test (1 in 5 tests, roughly), on line 65 of TestZActor.

java version "1.7.0_55"
Java(TM) SE Runtime Environment (build 1.7.0_55-b13)
Java HotSpot(TM) 64-Bit Server VM (build 24.55-b03, mixed mode)

**Comment by sbanacho** [comment]
Stack dump while it is stuck:  

Main thread (in unit test):

"main" prio=5 tid=0x00007fc683002800 nid=0x1303 runnable [0x0000000104532000]
   java.lang.Thread.State: RUNNABLE
        at sun.nio.ch.KQueueArrayWrapper.kevent0(Native Method)
        at sun.nio.ch.KQueueArrayWrapper.poll(KQueueArrayWrapper.java:200)
        at sun.nio.ch.KQueueSelectorImpl.doSelect(KQueueSelectorImpl.java:103)
        at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:87)
        - locked <0x00000007d6b8f7c0> (a sun.nio.ch.Util$2)
        - locked <0x00000007d6b8f7b0> (a java.util.Collections$UnmodifiableSet)
        - locked <0x00000007d6b8f690> (a sun.nio.ch.KQueueSelectorImpl)
        at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:98)
        at zmq.Signaler.waitEvent(Signaler.java:148)
        at zmq.Mailbox.recv(Mailbox.java:105)
        at zmq.SocketBase.processCommands(SocketBase.java:828)
        at zmq.SocketBase.send(SocketBase.java:666)
        at org.zeromq.ZMQ$Socket.send(ZMQ.java:1302)
        at org.zeromq.ZMQ$Socket.send(ZMQ.java:1276)
        at org.zeromq.TestZActor.testMinimalistic(TestZActor.java:65)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

Other ZMQ threads:

"iothread-2" daemon prio=5 tid=0x00007fc682038000 nid=0x5113 runnable [0x000000011070d000]
   java.lang.Thread.State: RUNNABLE
        at sun.nio.ch.KQueueArrayWrapper.kevent0(Native Method)
        at sun.nio.ch.KQueueArrayWrapper.poll(KQueueArrayWrapper.java:200)
        at sun.nio.ch.KQueueSelectorImpl.doSelect(KQueueSelectorImpl.java:103)
        at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:87)
        - locked <0x00000007d6b86e80> (a sun.nio.ch.Util$2)
        - locked <0x00000007d6b86e70> (a java.util.Collections$UnmodifiableSet)
        - locked <0x00000007d6b86d50> (a sun.nio.ch.KQueueSelectorImpl)
        at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:98)
        at zmq.Poller.run(Poller.java:216)
        at java.lang.Thread.run(Thread.java:745)

"reaper-1" daemon prio=5 tid=0x00007fc68280b800 nid=0x4b13 runnable [0x000000011060a000]
   java.lang.Thread.State: RUNNABLE
        at sun.nio.ch.KQueueArrayWrapper.kevent0(Native Method)
        at sun.nio.ch.KQueueArrayWrapper.poll(KQueueArrayWrapper.java:200)
        at sun.nio.ch.KQueueSelectorImpl.doSelect(KQueueSelectorImpl.java:103)
        at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:87)
        - locked <0x00000007d6b861c8> (a sun.nio.ch.Util$2)
        - locked <0x00000007d6b861b8> (a java.util.Collections$UnmodifiableSet)
        - locked <0x00000007d6b86098> (a sun.nio.ch.KQueueSelectorImpl)
        at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:98)
        at zmq.Poller.run(Poller.java:216)
        at java.lang.Thread.run(Thread.java:745)

**Comment by fredoboulo** [comment]
In that precise case, the main context is still not closed, but the shadow context is or is about to be closed.
This is a test done after the exit of the actor, to test the behavior of sending a message via the raw control pipe. I originaly put it because there is a danger in using this raw pipe for precisely that reason.

To make it appear at every test, a simple loop like this is enough:
    @Test
    public void testRepeated()
    {
        for (int idx = 300; idx-- > 0; ) {
            testMinimalistic();
        }
    }
 
Given that, what to do next? The test obviously does not fit its purpose, it's possible for now to just remove the boom test in both methods, but still need to figure out how to test this danger properly. Breaking the thermometer will not help.

Anyway this pipe is closed (lines 55 and 58 ensure that), so send and recv methods of ZMQ.Socket may make an early return because the pipe is already closed, or ...

**Comment by trevorbernard** [comment]
TestZActor is certainly unstable. This issue is blocking the next release #360

**Comment by daveyarwood** [comment]
I removed the 2 `@Ignore` lines in TestZActor and ran the tests locally -- it still hangs.

Commenting out the "boom" lines as @fredoboulo mentioned above does fix it, even when adding in the `testRepeated` test that runs the test 300 times in a row. So, it is clear that what's described above is still an issue.

**Comment by daveyarwood** [comment]
I don't fully understand all the ZStar/ZActor stuff, but from what I can tell, this may have something to do with the fact that we're using locks. It may be worth building some sort of escape hatch that might allow us to break the lock when we want to -- say, after a timeout when running these tests.

**Comment by fredoboulo** [comment]
I just made a simpler test to put the problem into evidence:

```
...
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.CoreMatchers.notNullValue;
import static org.junit.Assert.assertThat;
...
public class TestZThread
...
    @Test
    public void testClosePipe()
    {
        ZContext ctx = new ZContext();
        IAttachedRunnable runnable = new IAttachedRunnable()
        {
            @Override
            public void run(Object[] args, ZContext ctx, Socket pipe)
            {
                pipe.recvStr();
                pipe.send("pong");
            }
        };
        Socket pipe = ZThread.fork(ctx, runnable);

        assertThat(pipe, notNullValue());

        boolean rc = pipe.send("ping");
        assertThat(rc, is(true));

        String pong = pipe.recvStr();

        assertThat(pong, is("pong"));

        try {
            rc = pipe.send("boom ?!");
            assertThat("pipe was closed pretty fast", rc, is(true));
        }
        catch (ZMQException e) {
            int errno = e.getErrorCode();
            assertThat("Expected exception has the wrong code", errno, is(ZError.ETERM));
        }

        ctx.destroy();
    }

```

It fails randomly.

**Comment by daveyarwood** [comment]
Hmm, in that code, isn't the issue that the sender is blocking waiting for a response?

**Comment by fredoboulo** [comment]
I digged into that, at it actually works as per the specification: the PAIR socket blocks on sending when there is no attached socket on the receiving side. So far so good, but it appears to me that control pipe may not be aware that the IAttachedRunnable has done its job in real use case, and that the matching PAIR is already closed (if the IAttachedRunnable ends up unexpectidely for instance). 

One simple way to prevent that is to add this line somewhere: pipe.setSendTimeout(0);
We could add it at ZActor level, or in ZThread, depending on how deep we want to fix this.

**Comment by daveyarwood** [comment]
Maybe I'm misunderstanding what you mean, but wouldn't we want to set it on the pipe in the hanging test? i.e.:

```java
pipe.setTimeOut(0);
rc = pipe.send("boom ?!");
```

I tried doing that and it fixed the hanging issue, but this test assertion failed:

```java
Assert.assertTrue("actor pipe was closed pretty fast", rc);
```

Is there a place in the ZActor/ZThread code where adding the `setTimeOut(0)` would fix the failing test?

**Comment by fredoboulo** [comment]
Yes, this is another possibility.

According to me, there is a place for debate as this socket is still following the spec.

If I can sum up,  if we decide to apply a fix (setSendTimeout is only the first one I found, there may be others), there could be 3 places in the code where to do so:
- in the test itself, like you said. It fixes the test but not solve the situation, aka users still have manually to set this option, so that involves to communicate about that in some way.

- in ZActor/ZStar/ZAgent, so it fixes the failing test where it was first detected, and users can transparently benefit from it, without impacting all users of ZThread.

- in ZThread, where [it is the closest to the creation of the pipe](https://github.com/zeromq/jeromq/blob/master/src/main/java/org/zeromq/ZThread.java#L92). As previously, users have the benefit of the fix without any change in their code.

In every case, the test has to slightly change, because send returning true is not always the case because of async closing. So either not checking for the return value, or make a sleep long enough before to ensure that pipe is closed on the other side, and assert for false. If the code is broken, the call with block anyway, so maybe use the DONTWAIT flag.

And maybe, maybe, I am overthinking the situation...

**Comment by daveyarwood** [comment]
I think I'm confused about what we're testing. What is the desired behavior when sending the "boom" message?

**Comment by fredoboulo** [comment]
Sorry I'm not clear enough.
My vision of the situation is that ZThread is used when someone wants to create a dedicated thread to handle all the life cycle of sockets: creation, send/receive, closing. This thread communicates itself with its outside environment with another socket, an inproc pair, denominated as a pipe.

The problem as I see it, is that it may happen that this thread ends without the knowledge of the outside env. When this happens, it is impossible to use the pipe anymore, as it will hang indefinitely when trying to send a message to a no-more existing pair. It is a common and legitimate situation according to me.

I would expect the behaviour of the pipe to not block indefinitely and rather send a specific status.  If it is considered as non useful, I will be personally be OK, as this sendTimeOut(0); solves the situation for me.

**Comment by daveyarwood** [comment]
That all makes sense to me. It does feel like a legitimate use case.

Throwing an idea out there: what if the socket returned by pipe() were a
subclass of Socket that has context about whether the ZThread runnable has
ended, and throws a special exception (or returns a special value) if it
receives a message in that scenario?

**Comment by daveyarwood** [comment]
> #275: did not appear for quite some time. Still suspects that Utils.findOpenPort() is not fully reliable.

@fredoboulo Are you saying you think this issue may have been resolved?

**Comment by fredoboulo** [comment]
The issue was arising because send() was called shortly after context was closed.
My bad, I got confused with another test that was failing, it is not related to Utils.findOpenPort().

The test has changed, the dreaded "send boom" code is now removed. I think we can close that one. Feel free to reopen a new one if the issue persists.
