### ISSUE TITLE
ArrayIndexOutOfBounds

### ISSUE THREAD

**Issue by clixtec** [zeromq/jeromq#276]
I've been seeing an issue sporadically with JeroMQ not being able to send messages - and once it starts doing that the app is hosed.  I haven't been able to pin down the situation that causes it, but I'm filing this report anyway in the hopes that the stack trace gives you some clues.

The architecture of the app is separate processes A, B, and C, all communicating by pub/sub via a broker as in the ZeroMQ Guide, Figure 13 - Pub-Sub Network with a Proxy.

Thanks in advance for any assistance.

Sean

java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
    at java.util.ArrayList.rangeCheck(ArrayList.java:653) ~[?:1.8.0_31]
    at java.util.ArrayList.get(ArrayList.java:429) ~[?:1.8.0_31]
    at zmq.Dist.distribute(Dist.java:175) ~[jeromq-0.3.6-SNAPSHOT.jar:?]
    at zmq.Dist.sendToMatching(Dist.java:154) ~[jeromq-0.3.6-SNAPSHOT.jar:?]
    at zmq.XPub.xsend(XPub.java:195) ~[jeromq-0.3.6-SNAPSHOT.jar:?]
    at zmq.SocketBase.send(SocketBase.java:641) ~[jeromq-0.3.6-SNAPSHOT.jar:?]
    at org.zeromq.ZMQ$Socket.send(ZMQ.java:1302) ~[jeromq-0.3.6-SNAPSHOT.jar:?]
    at org.zeromq.ZMQ$Socket.send(ZMQ.java:1276) ~[jeromq-0.3.6-SNAPSHOT.jar:?]

**Comment by miniway** [comment]
If `ZMQ$Socket` is shared between threads, this could happen. Otherwise, could you upload a reproducible code?

**Comment by clixtec** [comment]
That was exactly it, there was a subtle sharing I hadn't expected!
Thanks for your help.

**Comment by clixtec** [comment]
I spoke too soon... under load the problem came back.  I will try to create a test case.

**Comment by upio** [comment]
I'm seeing this in 0.3.5

How to reproduce:

- Have a ZMQ.PUB socket (JVM 1)
- Have a ZMQ.SUB socket connect to the PUB topic and subscribe to > 750 topics (JVM 2)
- Restart the ZMQ.PUB server (JVM 1)
- socket.recvStr() in JVM 2 will throw IndexOutOfBoundsException

``` scala
object ZServer extends App {
  import org.zeromq.ZMQ

  val context = ZMQ.context(1)
  val socket = context.socket(ZMQ.PUB)
  socket.bind("tcp://*:5000")

  Thread.sleep(60 * 60 * 1000) // just block
}
```

``` scala
object ZClient extends App {
  import org.zeromq.ZMQ

  val context = ZMQ.context(1)
  val socket = context.socket(ZMQ.SUB)
  socket.connect("tcp://localhost:5000")

  for (i <- 0 to 750) { // any less and the bug is not triggered
    socket.subscribe(i.toString.getBytes(ZMQ.CHARSET))
  }

  while (!Thread.currentThread.isInterrupted) {
    socket.recvStr()
  }
}
```

```
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at java.util.ArrayList.rangeCheck(ArrayList.java:635)
	at java.util.ArrayList.get(ArrayList.java:411)
	at zmq.Utils.swap(Utils.java:124)
	at zmq.Dist.activated(Dist.java:129)
	at zmq.XSub.xwriteActivated(XSub.java:112)
	at zmq.SocketBase.writeActivated(SocketBase.java:1028)
	at zmq.Pipe.processActivateWrite(Pipe.java:302)
	at zmq.ZObject.processCommand(ZObject.java:61)
	at zmq.SocketBase.processCommands(SocketBase.java:863)
	at zmq.SocketBase.recv(SocketBase.java:751)
	at org.zeromq.ZMQ$Socket.recv(ZMQ.java:1359)
	at org.zeromq.ZMQ$Socket.recvStr(ZMQ.java:1430)
	at org.zeromq.ZMQ$Socket.recvStr(ZMQ.java:1420)
	at ioc.ZClient$delayedInit$body.apply(Scratch.scala:107)
	at scala.Function0$class.apply$mcV$sp(Function0.scala:40)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App$$anonfun$main$1.apply(App.scala:71)
	at scala.App$$anonfun$main$1.apply(App.scala:71)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:32)
	at scala.App$class.main(App.scala:71)
```

**Comment by bahostetterlewis** [comment]
I am running into the same issue as @upio - is there any update on a fix for this?

**Comment by daveyarwood** [comment]
As of 0.3.6, zmq.Utils.swap has been replaced with java.util.Collections.swap -- see [this commit](https://github.com/zeromq/jeromq/commit/12befcb27f13572a5a49669e433a399c3e5a72ac).

@upio / @bahostetterlewis: Can you confirm whether you have the same problem with JeroMQ 0.3.6?

@clixtec has what I think is a separate issue, as it is a different stacktrace. The code still appears to follow the same path in 0.3.6 and on master, so I suspect there is still a bug there.

**Comment by daveyarwood** [comment]
Haven't heard back from @upio or @bahostetterlewis, and I still think it's possible that the commit I mentioned above fixed their issue.

As for the original issue in this thread, @miniway pointed out that this scenario can happen if multiple threads are sharing a socket, which is not something JeroMQ supports. @clixtec noted that that was the issue exactly, so I think this can be closed.
