### ISSUE TITLE
NullPointerException when binding on an already used port while using a monitor

### ISSUE THREAD

**Issue by gbonnefille** [zeromq/jeromq#291]
We get a NullPointerException when trying to bind to an already used port.
This occurs when the socket has a monitor.

The code seems to try to send a CLOSED event to the monitor while the address field was not set.

**Comment by gbonnefille** [comment]
Please, consider the demo code hosted on https://github.com/gbonnefille/jeromq/tree/issue-291

**Comment by daveyarwood** [comment]
@gbonnefille Are you still experiencing this problem using the latest version of JeroMQ?

**Comment by gbonnefille** [comment]
With the current (`master` branch) version of JeroMQ, when running the `TestPairTcp` hacked on https://github.com/gbonnefille/jeromq/tree/issue-291 I still encounter a NullPointerException.

```
java.lang.NullPointerException: null
	at zmq.ZMQ$Event.write(ZMQ.java:222)
	at zmq.SocketBase.monitorEvent(SocketBase.java:1297)
	at zmq.SocketBase.event(SocketBase.java:1283)
	at zmq.SocketBase.eventClosed(SocketBase.java:1262)
	at zmq.io.net.tcp.TcpListener.close(TcpListener.java:141)
	at zmq.io.net.tcp.TcpListener.setAddress(TcpListener.java:194)
	at zmq.SocketBase.bind(SocketBase.java:363)
	at zmq.ZMQ.bind(ZMQ.java:379)
	at zmq.TestPairTcp.testPairTpcSecondServer(TestPairTcp.java:75)
```

**Comment by fredoboulo** [comment]
Woopsie doopsie, the test was indeed irrelevant. Please check that the added test in #492 reflects your use case, as it is slightly different from your original one.
