### ISSUE TITLE
jdk select bug

### ISSUE THREAD

**Issue by solq360** [zeromq/jeromq#338]
test 

```
    @Test
    public void pushPullTest() throws InterruptedException {

    try (final ZSocket pull = new ZSocket(ZMQ.PULL); final ZSocket push = new ZSocket(ZMQ.PUSH)) {
        pull.bind("tcp://*:7210");
        push.connect("tcp://127.0.0.1:7210");

        final int count = 300000;
        Thread t= new Thread(new Runnable() {
        public void run() {
            int v = 0;
            String actual = null;
            int _count = count;
            while (_count-- > 0) {
            actual = pull.receiveStringUtf8();
            v++;
            }
            System.out.println(actual);
        }
        });
        t.start();

        final String expected = "hello";
        long start = System.currentTimeMillis();
        for (int i = 0; i < count; i++) {
        push.sendStringUtf8(expected + "_" + i);
        }
        long end = System.currentTimeMillis();
        System.out.println("push time :" + (end - start));

        t.join();
        end = System.currentTimeMillis();
        System.out.println("all time :" + (end - start));
    }
    }
```

dead lock 

```

    at sun.nio.ch.SelectorImpl.select(Unknown Source)
    at zmq.Signaler.waitEvent(Signaler.java:148)
    at zmq.Mailbox.recv(Mailbox.java:105)
    at zmq.SocketBase.processCommands(SocketBase.java:796)
    at zmq.SocketBase.recv(SocketBase.java:719)
    at org.zeromq.ZSocket.receive(ZSocket.java:212)
    at org.zeromq.ZSocket.receiveStringUtf8(ZSocket.java:223)
    at org.zeromq.ZSocket.receiveStringUtf8(ZSocket.java:218)
    at org.zeromq.ZSocketTest$2.run(ZSocketTest.java:60)
    at java.lang.Thread.run(Unknown Source)

   Locked ownable synchronizers:

    - locked <0x00000000d7a71330> (a sun.nio.ch.Util$2)
    - locked <0x00000000d7a71320> (a java.util.Collections$UnmodifiableSet)
    - locked <0x00000000d7a5c820> (a sun.nio.ch.WindowsSelectorImpl)
    at sun.nio.ch.SelectorImpl.select(Unknown Source)
    at zmq.Poller.run(Poller.java:216)
    at java.lang.Thread.run(Unknown Source)

   Locked ownable synchronizers:
```

```
 public boolean waitEvent(long timeout)
    {
        int rc = 0;

        try {
            if (timeout == 0) {
                // waitEvent(0) is called every read/send of SocketBase
                // instant readiness is not strictly required
                // On the other hand, we can save lots of system call and increase performance
                return rcursor < wcursor.get();

            }
            else if (timeout < 0) {
                rc = selector.select(0);
            }
            else {
                rc = selector.select(timeout);
            }
        }
        catch (IOException e) {
            throw new ZError.IOException(e);
        }

        if (rc == 0) {
            return false;
        }

        selector.selectedKeys().clear();

        return true;
    }
```

作者用了jdk nio 来做网络处理而jdk 本身是有BUG的，当数据量一大了，或时间长了就出现卡死现象

**Comment by solq360** [comment]
建议改为 netty 吧，，不过这工作量就大了

**Comment by lion117** [comment]
I had the same same problem. 
------------------------
> I did some debug in the **HWclient / HWserver** the simplest java demo
In the **req-rep**  module , when the **request frequency increase** (only one client to request to server ), server was easy to get crash , no response to  any request . 

------------------------
>  Are the any silver bullet to avoid such a issue?

**Comment by daveyarwood** [comment]
@solq360 / @lion117: Are you still experiencing this issue on the latest version of JeroMQ?

**Comment by daveyarwood** [comment]
There has been no activity on this issue in the last 2-1/2 years, no confirmation that the issue still exists in the latest release of JeroMQ. Closing this issue for now, feel free to reopen if the issue persists with the latest version.
