### ISSUE TITLE
java.lang.IllegalArgumentException: subscription flag

### ISSUE THREAD

**Issue by zhivko** [zeromq/jeromq#345]
I am getting error:
```
Exception in thread "Thread-1" java.lang.IllegalArgumentException: subscription flag
	at zmq.XSub.xsend(XSub.java:136)
	at zmq.SocketBase.send(SocketBase.java:641)
	at org.zeromq.ZMQ$Socket.send(ZMQ.java:1302)
	at com.kz.pipeCutter.BBB.BBBHalRComp.run(BBBHalRComp.java:98)
	at java.lang.Thread.run(Thread.java:745)
```

I believe this is happening in:
```
    protected boolean xsend(Msg msg)
    {
        byte[] data = msg.data();
        // Malformed subscriptions.
        if (data.length < 1 || (data[0] != 0 && data[0] != 1)) {
            throw new IllegalArgumentException("subscription flag");
        }
```

What is the reason behind:
```data[0] != 0 && data[0] != 1``` ?

Is this something that is part of http://api.zeromq.org/ ? If yes can you point me to specification where this condition is described? 

If I try to subscribe to all topics for XSUB type of sockets like this:
```
private void getClient() {
    ctx = ZMQ.context(1);

    //  Socket to send messages to
		client = ctx.socket(ZMQ.XSUB);
		String identity = String
				.format("%04X-%04X", rand.nextInt(), rand.nextInt());
		client.setIdentity(identity.getBytes(ZMQ.CHARSET));
		client.setLinger(0);
		client.subscribe("".getBytes(ZMQ.CHARSET));
		client.connect(this.halRCompUri);
	}
˙``
I get:
```
Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException: Unknown Option 6
	at zmq.Options.setSocketOpt(Options.java:373)
	at zmq.SocketBase.setSocketOpt(SocketBase.java:247)
	at org.zeromq.ZMQ$Socket.setsockopt(ZMQ.java:446)
	at org.zeromq.ZMQ$Socket.subscribe(ZMQ.java:1024)
	at com.kz.pipeCutter.BBB.BBBHalRComp.getClient(BBBHalRComp.java:158)
	at com.kz.pipeCutter.BBB.BBBHalRComp.<init>(BBBHalRComp.java:44)
```

From: https://github.com/zeromq/rfc/blob/master/29/README.md
The XSUB Socket Type
The XSUB socket type extends the SUB socket with the ability to send messages and subscription commands upstream to publishers. XSUB is usually used in proxies but is also useful for advanced applications.
General behavior:
MAY be connected to any number of PUB or XPUB publishers, and MAY both send and receive messages.

so is there an example to send message with XSUB type socket?

**Comment by zhivko** [comment]
Such subscription need to prefixed by 1 character like "1" + subscrtiption and then no error is received.

**Comment by komape** [comment]
@zhivko Can you explain this in detail?

The problem is not the topic the xSub socket tries to connect but rather that "Subscribe" is not an option itself.
