### ISSUE TITLE
Fatal Android Exception If JeroMQ Cannot Connect To Server

### ISSUE THREAD

**Issue by T-Spoon** [zeromq/jeromq#349]
```
zmq.ZError$IOException: java.net.SocketException: sendto failed: EPIPE (Broken pipe)
     at zmq.Signaler.send(Signaler.java:124)
     at zmq.Mailbox.send(Mailbox.java:85)
     at zmq.Ctx.sendCommand(Ctx.java:388)
     at zmq.ZObject.sendCommand(ZObject.java:362)
     at zmq.ZObject.sendHiccup(ZObject.java:226)
     at zmq.Pipe.hiccup(Pipe.java:541)
     at zmq.SessionBase.detached(SessionBase.java:462)
     at zmq.SessionBase.detach(SessionBase.java:378)
     at zmq.XSub$XSubSession.detach(XSub.java:24)
     at zmq.StreamEngine.error(StreamEngine.java:601)
     at zmq.StreamEngine.inEvent(StreamEngine.java:342)
     at zmq.IOObject.inEvent(IOObject.java:105)
     at zmq.Poller.run(Poller.java:247)
     at java.lang.Thread.run(Thread.java:818)
  Caused by: java.net.SocketException: sendto failed: EPIPE (Broken pipe)
     at libcore.io.IoBridge.maybeThrowAfterSendto(IoBridge.java:546)
     at libcore.io.IoBridge.sendto(IoBridge.java:529)
     at java.nio.SocketChannelImpl.writeImpl(SocketChannelImpl.java:406)
     at java.nio.SocketChannelImpl.write(SocketChannelImpl.java:364)
     at java.nio.PipeImpl$PipeSinkChannel.write(PipeImpl.java:114)
     at zmq.Signaler.send(Signaler.java:121)
     at zmq.Mailbox.send(Mailbox.java:85) 
     at zmq.Ctx.sendCommand(Ctx.java:388) 
     at zmq.ZObject.sendCommand(ZObject.java:362) 
     at zmq.ZObject.sendHiccup(ZObject.java:226) 
     at zmq.Pipe.hiccup(Pipe.java:541) 
     at zmq.SessionBase.detached(SessionBase.java:462) 
     at zmq.SessionBase.detach(SessionBase.java:378) 
     at zmq.XSub$XSubSession.detach(XSub.java:24) 
     at zmq.StreamEngine.error(StreamEngine.java:601) 
     at zmq.StreamEngine.inEvent(StreamEngine.java:342) 
     at zmq.IOObject.inEvent(IOObject.java:105) 
     at zmq.Poller.run(Poller.java:247) 
     at java.lang.Thread.run(Thread.java:818) 
  Caused by: android.system.ErrnoException: sendto failed: EPIPE (Broken pipe)
     at libcore.io.Posix.sendtoBytes(Native Method)
     at libcore.io.Posix.sendto(Posix.java:171)
     at libcore.io.BlockGuardOs.sendto(BlockGuardOs.java:270)
     at libcore.io.IoBridge.sendto(IoBridge.java:527)
     at java.nio.SocketChannelImpl.writeImpl(SocketChannelImpl.java:406) 
     at java.nio.SocketChannelImpl.write(SocketChannelImpl.java:364) 
     at java.nio.PipeImpl$PipeSinkChannel.write(PipeImpl.java:114) 
     at zmq.Signaler.send(Signaler.java:121) 
     at zmq.Mailbox.send(Mailbox.java:85) 
     at zmq.Ctx.sendCommand(Ctx.java:388) 
     at zmq.ZObject.sendCommand(ZObject.java:362) 
     at zmq.ZObject.sendHiccup(ZObject.java:226) 
     at zmq.Pipe.hiccup(Pipe.java:541) 
     at zmq.SessionBase.detached(SessionBase.java:462) 
     at zmq.SessionBase.detach(SessionBase.java:378) 
     at zmq.XSub$XSubSession.detach(XSub.java:24) 
     at zmq.StreamEngine.error(StreamEngine.java:601) 
     at zmq.StreamEngine.inEvent(StreamEngine.java:342) 
     at zmq.IOObject.inEvent(IOObject.java:105) 
     at zmq.Poller.run(Poller.java:247) 
     at java.lang.Thread.run(Thread.java:818) 
```

If the ZeroMQ server cannot be reached after a certain amount of time, the ZeroMQ thread crashes the whole Android application. 

There should be a way to fail gracefully and retry the connection (without resorting to `Thread. setDefaultUncaughtExceptionHandler`).

**Comment by hpsaturn** [comment]
same situation but problem it seems to be on subscriptions.
```java
    private class ZeroMQSubscription implements Runnable {

        private final OnSubscriptionCallBack cb;

        public ZeroMQSubscription(OnSubscriptionCallBack cb) {
            this.cb=cb;
        }

        @Override
        public void run() {
            try {
                ZMQ.Context sub_context = ZMQ.context(1);
                ZMQ.Socket sub_socket = sub_context.socket(ZMQ.SUB);
                sub_socket.connect(target.getSubPort());
                sub_socket.subscribe("".getBytes());

                if(DEBUG)Log.i(TAG,"subscribe with: "+ target.getSubPort());

                while(!Thread.currentThread().isInterrupted()) {
                    try {
                        if(sub_context!=null&&sub_socket!=null){
                            cb.onReceiveData(target.getHost(),sub_socket.recv());
                        }
                    } catch (Exception e) {
                        if(DEBUG)Log.e(TAG,"ZeroMQSubscription onReceiveData crash: "+e.getMessage());
                        e.printStackTrace();
                    }
                }
                if(DEBUG)Log.e(TAG,"ZeroMQSubscription finishing..");
                sub_socket.close();
                sub_context.term();
            } catch (ZError.IOException e) {
                if(DEBUG)Log.e(TAG,"ZeroMQSubscription IOException: "+e.getMessage());
                e.printStackTrace();
            }
        }
    }
```

**Comment by PulkitSethi1984** [comment]
Has anyone had any luck recovering from this defect gracefully

**Comment by trevorbernard** [comment]
@T-Spoon @PulkitSethi1984 @hpsaturn Is this still an issue with the latest stable release?

**Comment by daveyarwood** [comment]
It's been almost 2 years since the last update. No confirmation that this issue persists with the latest release of JeroMQ, so closing for now. Feel free to reopen if this is still an issue with the latest release.
