### ISSUE TITLE
Flow of events in PUSH-PULL pipe stops intermittently

### ISSUE THREAD

**Issue by sidgod** [zeromq/jeromq#355]
We are using version 0.3.4 of JeroMQ.

We have a setup where Jero MQ channel is being used in PUSH-PULL mode. There is a continuous flow of events from PUSH side, PULL side reads events off pipe and processes the same. PULL side has been configured with small receive timeout (10ms). Every time we run test, event flow stops after 48+ hrs. At socket level connection is always in "ESTABLISHED" state. When I ran "ss" utility I can see socket queue full from PUSH side of process.

Stack trace on PUSH side is as follows:
java.lang.Thread.State: RUNNABLE
    at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
    at sun.nio.ch.EPollArrayWrapper.poll(Unknown Source)
    at sun.nio.ch.EPollSelectorImpl.doSelect(Unknown Source)
    at sun.nio.ch.SelectorImpl.lockAndDoSelect(Unknown Source)
    - locked <0x00000000c2b495b0> (a sun.nio.ch.Util$2)
    - locked <0x00000000c2b495a0> (a java.util.Collections$UnmodifiableSet)
    - locked <0x00000000c2b493b8> (a sun.nio.ch.EPollSelectorImpl)
    at sun.nio.ch.SelectorImpl.select(Unknown Source)
    at zmq.Signaler.wait_event(Signaler.java:135)
    at zmq.Mailbox.recv(Mailbox.java:105)
    at zmq.SocketBase.process_commands(SocketBase.java:793)
    at zmq.SocketBase.send(SocketBase.java:635)
    at org.zeromq.ZMQ$Socket.send(ZMQ.java:1206)

Stack trace on PULL side is as follows:
java.lang.Thread.State: RUNNABLE
    at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
    at sun.nio.ch.EPollArrayWrapper.poll(Unknown Source)
    at sun.nio.ch.EPollSelectorImpl.doSelect(Unknown Source)
    at sun.nio.ch.SelectorImpl.lockAndDoSelect(Unknown Source)
    - locked <0x00000005c1d0bcf8> (a sun.nio.ch.Util$2)
    - locked <0x00000005c1d0bce8> (a java.util.Collections$UnmodifiableSet)
    - locked <0x00000005c1d0bd08> (a sun.nio.ch.EPollSelectorImpl)
    at sun.nio.ch.SelectorImpl.select(Unknown Source)
    at zmq.Signaler.wait_event(Signaler.java:137)
    at zmq.Mailbox.recv(Mailbox.java:105)
    at zmq.SocketBase.process_commands(SocketBase.java:793)
    at zmq.SocketBase.recv(SocketBase.java:714)
    at org.zeromq.ZMQ$Socket.recv(ZMQ.java:1247)

Has anyone seen any such issue ? Does anyone know of anything else that I can try out ?

**Comment by daveyarwood** [comment]
Closing this for now. Feel free to reopen if it is still an issue using the latest release.
