### ISSUE TITLE
 Signaler.recv() assert nbytes == 1 Exception

### ISSUE THREAD

**Issue by maxid** [zeromq/jeromq#361]
why Signaler.recv() assert nbytes == 1 ?

Exception:

java.lang.AssertionError
	at zmq.Signaler.recv(Signaler.java:173)
	at zmq.Mailbox.recv(Mailbox.java:101)
	at zmq.SocketBase.processCommands(SocketBase.java:864)
	at zmq.SocketBase.send(SocketBase.java:627)
	at org.zeromq.ZMQ$Socket.send(ZMQ.java:1302)
	at org.zeromq.ZMQ$Socket.send(ZMQ.java:1276)
	at .........zmqPublisher(ZmqTest.java:32)

Test code:

    private final static String sample = "0000000000000|20160920184332|000000|0000|0|0|";

    @Before
    public void before() {
        TrafficLimits.create("test", 3e6);
    }

    @Test
    public void zmqPublisher() throws Exception {
        // Prepare our context and publisher
        ZMQ.Context context = ZMQ.context(1);
        ZMQ.Socket publisher = context.socket(ZMQ.PUB);

        publisher.bind("tcp://*:5563");

        while (!Thread.currentThread().isInterrupted()) {
            // Write two messages, each with an envelope and content
            TrafficLimits.acquire("test");
            publisher.send(sample);
        }

        publisher.close();
        context.term();

    }

    @Test
    public void zmqTest() {
        ZMQ.Context context = ZMQ.context(1);
        //  Socket to talk to server
        ZMQ.Socket subscriber = context.socket(ZMQ.SUB);
        subscriber.connect("tcp://127.0.0.1:5563");
        subscriber.subscribe("".getBytes());

        System.out.println("launch and connect client.");

        try {
            double count = 1e6;
            long start = 0;
            int i = 0;
            int sampleLen = sample.length();
            while (true) {
                if (i > 0 && i % count == 0) {
                    long end = Mixeds.endCost(start);
                    System.out.println(String.format("cost: %sms, qps: %s", end, count / end * 1000));
                    start = Mixeds.startCost();
                }
                String recv = subscriber.recvStr(0);
                if(recv.length() != sampleLen) System.out.println("...........................");
                if (start == 0) start = Mixeds.startCost();
                i++;
            }
        } finally {
            //  We never get here but clean up anyhow
            subscriber.close();
            context.term();
        }

    }

**Comment by bvella** [comment]
pull request #374 should fix this. I have a test that passes successfully on linux but hands in windows due to that assert. reverted to how it was pre 0.3.5, i.w. while loop until nbytes == 1

**Comment by daveyarwood** [comment]
@maxid Is this still an issue with the latest version of JeroMQ?
