### ISSUE TITLE
TestAddress fails on Mac/Java8 builds

### ISSUE THREAD

**Issue by trequartista10** [zeromq/jeromq#369]
Hi,

Is it ok to remove TestAddress.invaid() test. It does not pass the tests. 

java.lang.AssertionError: Expected exception: java.lang.IllegalArgumentException

```
at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:32)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:117)
at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:253)
at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:84)
```

**Comment by c-rack** [comment]
@trequartista10 I cannot reproduce this issue, all tests pass on my Mac with JDK 8 installed.
Generally, I would rather recommend to fix the problem instead of removing a failing test. Maybe you could send a PR to extend Travis-CI config with OS X/JDK8 to see if it is failing also there?

**Comment by daveyarwood** [comment]
I cannot reproduce the issue either. After changing `.java-version` to use 1.8 instead of 1.7 and running `mvn test`, all 88 tests still pass on my Mac with JRE 1.8.0_25.

It would be interesting to see what the "valid" arguments were that made that test (expecting invalid arguments) fail.

**Comment by daveyarwood** [comment]
I made a PR to add oraclejdk8 to the Travis build environments. All tests passed except 1, but it wasn't the one reported by @trequartista10. See #370 for more detail on the test that failed.

**Comment by trevorbernard** [comment]
Unable to recreate
