### ISSUE TITLE
PUSH/PULL Blocking nature

### ISSUE THREAD

**Issue by pdoro** [zeromq/jeromq#410]
I'm having a issue regarding the blocking nature of PUSH/PULL sockets.

Here is a [gist](https://gist.github.com/pdoro/f70de75aee9e2c51d56654b273693ee0) with an example.

I've made a slight variation of taskvent where the dispatcher sends 15k messages each one about 500B size to a push socket. The workers (2 in my gist) receive the message from their own pull socket, then they sleep for 2msec and finally forward the message to the collector. The collector just receives the messages and signals the dispatcher to finish with a REQ/REP socket.

In my example, the collector never receives all the messages but if I decrease the message size to say 50B then all the messages arrive to the collector. From the ZMQ documentation, PUSH/PULL sockets block messages when their HWM are reached and the kernel buffers are full. I expect all the messages to arrive to the collector no matter the size of the message. Obviously, larger messages should trigger HWM limits sooner, but not block indefinitely the stream.

This situation may be related with #379, #314 or #355

Note that altough I'm using threads for the example, the push/pull sockets are not shared between them.

**Comment by daveyarwood** [comment]
I believe HWM is something you need to opt into by setting a HWM value -- see [TestHwm.java](https://github.com/zeromq/jeromq/blob/59458bc1379098227455c19b22abadd47294adfc/src/test/java/zmq/TestHwm.java). I don't see in your code where you are setting a HWM.

Also, according to [this](http://api.zeromq.org/2-1:zmq-setsockopt#toc3):

> The high water mark is a hard limit on **the maximum number of outstanding messages** ØMQ shall queue in memory for any single peer that the specified socket is communicating with.

AFAICT, the HWM has to do with the number of queued messages, not the sum of their sizes.

**Comment by pdoro** [comment]
Thanks for the quick response.

I've modified my [gist](https://gist.github.com/pdoro/f70de75aee9e2c51d56654b273693ee0) and tested using a 1000 HWM for both PUSH and PULL sockets but there's no difference at all.

You're right that the HWM sets a hard limits for messages not their sizes. But the kernel buffers are set using bytes so larger messages should block kernel buffers sonner.

**Comment by pdoro** [comment]
I've been debugging the send method from a PUSH socket down to the Push and Pipe classes. The Push class has a LB attribute that contains a List of Pipes. Each Pipe store it's HWM. The LB class get's the current Pipe [here](https://github.com/zeromq/jeromq/blob/master/src/main/java/zmq/LB.java#L83), calls the write method that first of all checks the HWM [here](https://github.com/zeromq/jeromq/blob/master/src/main/java/zmq/Pipe.java#L207). When the HWM is reached, xsend returns false so the socket enters a special mode where it tries to processsend the message in an infinite loop [here](https://github.com/zeromq/jeromq/blob/master/src/main/java/zmq/SocketBase.java#L619)

Seem's the code for HWM limits is implemented but I guess something is missing...

**Comment by daveyarwood** [comment]
I don't think I'm understanding the problem. PUSH/PULL sockets are supposed to block when the HWM is met, right?

**Comment by pdoro** [comment]
Yes, but not infinitely. AFAIK when a HWM is reached in a PUSH socket, it enters a special mode where it tries to send the pending message infinitely. On the other end a PULL socket is pulling messages forever so the stream of messages has no reason for being blocked.

**Comment by fredoboulo** [comment]
I just tested briefly your code, and I do not see yet the blocking problem. However, the gist code is not connecting/binding the kill channels in both dispatcher and collector (lines 31 & 116).
After fixing that, adding some latch to coordinate the threads and some console messages, I can repeatedly test the dispatching and collecting of all 15k messages of 500B. Only the end of the process seems to be problematic in that case, not the sending/receiving messages part, but I may have missed something.

**Comment by pdoro** [comment]
Hello @fredoboulo. I'm actually surprised that you haven't experienced the blocking issue. You're absolutely right that the kill channel was not correctly connect/bind but that was not a problem for me as it was never used due to the infinite block. I've updated the [gist](https://gist.github.com/pdoro/f70de75aee9e2c51d56654b273693ee0) with the correct bind for the kill channel.

I'm using JRE 1.8.0_101 in Windows-10 64bit FYI

**Comment by fredoboulo** [comment]
Hello @pdoro, I noticed the blocking behaviour, but could not see it as an issue, as I consider it part of the normal behaviour.

Please have a look [at this gist] (https://gist.github.com/fredoboulo/b15e8933d7dbc04d65c3c6d0cee9d8da)
I modified yours to start make it a JUnit test.

Please correct me if I'm wrong I will try to reformulate what you said: the main issue you noticed was that the collector was not receiving all messages when they have a size bigger than 50B. Talking about the blocking behaviour of the push/pull socket is a next step in your analysis. However, I cannot demonstrate it: the sample code [in the gist] (https://gist.github.com/fredoboulo/b15e8933d7dbc04d65c3c6d0cee9d8da), based on yours, works in the sense that all 15000 messages are received by the collector. The gist code you provided was not able to finish properly as the kill channel was not effective. Could it be that point that made you think that the collector was not receiving all messages?

**Comment by pdoro** [comment]
Hello @fredoboulo. I've tested your code and works for me but I've noticed you used the latest API that is not available at [maven central](https://mvnrepository.com/artifact/org.zeromq/jeromq) nor [central repository](http://search.maven.org/#search%7Cga%7C1%7Cjeromq).

I don't think that the misuse of the kill channel was the root of my problem because in that case the collector should hace received all the messages and dispatcher would have get stuck in the recv call or simply close the sockets but this didn't happened at all. Instead, dispatcher sent up to message number 10999, collector procesed it, and then both blocked. A thread dump show they blocked at send and recv respectively.

Using the latest version of the respository may be the solution but I still don't know why v0.3.6 blocks the stream. The only difference as far as I can tell is that you use a CountDownLatch to synchronize the start and a Poller (I used ZMQ.Poller previously the same way you did but got the same upsetting results). In my latest gist, the kill channel is correctly used AFAIK and the blocking behaviour is still present.

I could improve my gist to use a Poller and elaborarte more the kill channel synchronization but there's not point if a new version is going to be released in the near future.

As you said before, the blocking behaviour is correct for PUSH/PULL sockets and adhere to ZMQ standard but this block should not be indefinitely. The message size surprised me as smaller messages did complete the whole forwarding cycle but larger one blocked the stream so I thought it was a HWM/buffer issue.

Any idea?

**Comment by fredoboulo** [comment]
You're right, the CountdownLatch is a trick used to simplify the coordination between threads as they are so close to each other. I updated my gist to remove it and to use old version of poller.

Your sentence about the latest API is interesting. Which version are you using?

When looking at your code, I can see that the first message used to signal the start of the batch is sent to the wrong socket, maybe that can impact the behaviour on your side.

I would really be interested if we can pinpoint  and demonstrate the blocking mis-behaviour, especially on the sending part as you experienced it.

**Comment by pdoro** [comment]
Regarding the API version, I'm using version v0.3.6 right. The version you used in your previous gist created a Poller using a NIO Selector that you got from ZContext ([here](https://gist.github.com/fredoboulo/b15e8933d7dbc04d65c3c6d0cee9d8da/revisions#diff-354dc2f1097e05479b3c8972ebb6a1cbL124)) but v0.3.6 does not allow to get a Selector.

@fredoboulo. I created a minimal version of the code [here](https://gist.github.com/pdoro/7341eec68037b46f9543016ec49bcbf3). In order to avoid any synchronization bugs in my code I removed the kill channel and the start of batch signal. A CountDownLatch synchronizes the start of the stream plus a 1sec sleep in every thread to ensure they are all bind/connected after the latch is released. There's no thread end so any socket/context could be destroyed prematurely.

I just expect the dispatcher to send 15k messages and the collector to receive them, then they both block. 

When I ran this example using **v0.3.6**, Dispatcher send up to message number 13999 and blocked forever. Later I used the JMQ code from the cloned repository (**v0.4?**) to test this sample code and got the expected result in **every single test**!.

Here are their thread dumps from JMQv0.3.6 test:

**Dispatcher**
java.lang.Thread.State: RUNNABLE
...
	- locked <0x0000000082276898> (a sun.nio.ch.Util$2)
	- locked <0x0000000082276888> (a java.util.Collections$UnmodifiableSet)
	- locked <0x0000000082276450> (a sun.nio.ch.WindowsSelectorImpl)
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
	at zmq.Signaler.waitEvent(Signaler.java:129)
	at zmq.Mailbox.recv(Mailbox.java:86)
	at zmq.SocketBase.processCommands(SocketBase.java:777)
	at zmq.SocketBase.send(SocketBase.java:615)
	at org.zeromq.ZMQ$Socket.send(ZMQ.java:1271)
	at org.zeromq.ZMQ$Socket.send(ZMQ.java:1255)
	at com.deyde.TaskVentTest$Dispatcher.run([TaskVentTest.java:44](https://gist.github.com/pdoro/7341eec68037b46f9543016ec49bcbf3#file-taskventtest-java-L44))


**Worker 1 && 2**
java.lang.Thread.State: RUNNABLE
...
	- locked <0x00000000822e7598> (a sun.nio.ch.Util$2)
	- locked <0x00000000822e7588> (a java.util.Collections$UnmodifiableSet)
	- locked <0x00000000822e73c8> (a sun.nio.ch.WindowsSelectorImpl)
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
	at zmq.Signaler.waitEvent(Signaler.java:129)
	at zmq.Mailbox.recv(Mailbox.java:86)
	at zmq.SocketBase.processCommands(SocketBase.java:777)
	at zmq.SocketBase.send(SocketBase.java:615)
	at org.zeromq.ZMQ$Socket.send(ZMQ.java:1271)
	at org.zeromq.ZMQ$Socket.send(ZMQ.java:1255)
	at com.deyde.TaskVentTest$Worker.run([TaskVentTest.java:105](https://gist.github.com/pdoro/7341eec68037b46f9543016ec49bcbf3#file-taskventtest-java-L105))

**Collector**
java.lang.Thread.State: RUNNABLE
...
	- locked <0x0000000082270528> (a sun.nio.ch.Util$2)
	- locked <0x0000000082270518> (a java.util.Collections$UnmodifiableSet)
	- locked <0x0000000082270090> (a sun.nio.ch.WindowsSelectorImpl)
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
	at zmq.Signaler.waitEvent(Signaler.java:129)
	at zmq.Mailbox.recv(Mailbox.java:86)
	at zmq.SocketBase.processCommands(SocketBase.java:777)
	at zmq.SocketBase.recv(SocketBase.java:700)
	at org.zeromq.ZMQ$Socket.recv(ZMQ.java:1328)
	at com.deyde.TaskVentTest$Collector.run([TaskVentTest.java:145](https://gist.github.com/pdoro/7341eec68037b46f9543016ec49bcbf3#file-taskventtest-java-L145))

**Comment by fredoboulo** [comment]
Hello @pdoro, I got a problem of the same nature in a different context.

Can you try putting recv HWM of worker pull socket to 0 ? this will disable the "pipe full" mechanism.

Please tell us also some details about your environment (os, cores, ...), because I still do not understand why the same code is working on my machine and not on yours.

**Comment by daveyarwood** [comment]
Blocked pending answers to @fredoboulo 's questions from @pdoro.
