### ISSUE TITLE
NullPointerException when ZMQ_TCP_ACCEPT_FILTER is used

### ISSUE THREAD

**Issue by tjamesturner** [zeromq/jeromq#412]
if you call Options::setSocketOpt with zmq.ZMQ.ZMQ_TCP_ACCEPT_FILTER, it either has no effect (e.g. because everything matches the filter) or it causes a NullPointerException inside TcpListener. this NullPointerException escapes the Poller::run loop which prevents any future connections (and causes other problems).

here is a short self contained complete example:
```java
public void testAcceptFilter() throws Exception
{
	ZContext context = new ZContext();
	ZMQ.Socket socket = context.createSocket(ZMQ.SUB);
	socket.base().setSocketOpt(zmq.ZMQ.ZMQ_TCP_ACCEPT_FILTER, "8.8.8.8:8090");
	socket.bind("tcp://*:8090");
	ZMQ.Socket pubSocket = context.createSocket(ZMQ.PUB);
	pubSocket.connect("tcp://127.0.0.1:8090");
}
```
here is a sample stack trace produced by the above test:
```
Exception in thread "iothread-2" java.lang.NullPointerException
	at zmq.Utils.tuneTcpSocket(Utils.java:37)
	at zmq.TcpListener.acceptEvent(TcpListener.java:72)
	at zmq.IOObject.acceptEvent(IOObject.java:104)
	at zmq.Poller.run(Poller.java:231)
	at java.lang.Thread.run(Thread.java:745)
```

in order to fix the issue, we either need to add a null check to TcpListener::acceptEvent or throw an IOException from TcpListener::accept instead of returning null. i prefer the later solution and will submit a pull request shortly.

**Comment by tjamesturner** [comment]
pull request #413 has fixed this issue
