### ISSUE TITLE
Assertion in polling

### ISSUE THREAD

**Issue by eplumer** [zeromq/jeromq#418]
I am looking for any suggestions on what might be causing this exception:

  java.lang.AssertionError
  at zmq.Mailbox.recv(Mailbox.java:96)
  at zmq.SocketBase.processCommands(SocketBase.java:803)
  at zmq.SocketBase.inEvent(SocketBase.java:917)
  at zmq.Poller.run(Poller.java:228)
  at java.lang.Thread.run(Thread.java:745)

Sometimes, but not always, the assertion is prefix with this line:

  Exception in thread "reaper-1" java.lang.AssertionError

which correlates to code in Mailbox.java

  //  Get a command.
  cmd = cpipe.read();
  assert (cmd != null);   <<<<<<<<<<<<<<<<<<
  
  return cmd;

I get this sporadically in an application that is loosely similar to paranoid-pirates queue. I am guessing a timing or race condition but am not sure where to start.

**Comment by eplumer** [comment]
Using the latest examples, upgrade my application from jeromq 0.3.6 to 0.4.0 and changed to the Poller object.  My junit stress tests are no longer throwing this assertion.
