### ISSUE TITLE
Support for Android API Level < 24?

### ISSUE THREAD

**Issue by skipe777** [zeromq/jeromq#451]
The library (version 0.4.2) seems to leverage java.net.StandardProtocolFamily and java.net.StandardSocketOptions which are only available at API level 24 and greater. Is there a version of JeroMQ that operates on a lower API level then this (with Curve support)?

**Comment by fredoboulo** [comment]
I just made a PR to fix that. Could you test it with Android environment to be sure that no other point needs to be addressed for a successful compile?

**Comment by skipe777** [comment]
A bit more progress, still complaining about 24 or greater APIs:

`java.lang.NoClassDefFoundError: Failed resolution of: Ljava/nio/channels/NetworkChannel;
                                                                                at zmq.io.net.tcp.TcpListener.setAddress(TcpListener.java:186)
                                                                                at zmq.SocketBase.bind(SocketBase.java:363)
                                                                                at org.zeromq.ZMQ$Socket.bind(ZMQ.java:2333)`

**Comment by skipe777** [comment]
It doesn't make it to that call, it stops at setReuseAddress():

`Caused by: java.lang.ClassNotFoundException: Didn't find class "java.nio.channels.NetworkChannel" on path: DexPathList[[zip file "/data/app/com.futureskies.jeromqtest-1/base.apk", zip file "/data/app/com.futureskies.jeromqtest-1/split_lib_dependencies_apk.apk", zip file "/data/app/com.futureskies.jeromqtest-1/split_lib_slice_0_apk.apk", zip file "/data/app/com.futureskies.jeromqtest-1/split_lib_slice_1_apk.apk", zip file "/data/app/com.futureskies.jeromqtest-1/split_lib_slice_2_apk.apk", zip file "/data/app/com.futureskies.jeromqtest-1/split_lib_slice_3_apk.apk", zip file "/data/app/com.futureskies.jeromqtest-1/split_lib_slice_4_apk.apk", zip file "/data/app/com.futureskies.jeromqtest-1/split_lib_slice_5_apk.apk", zip file "/data/app/com.futureskies.jeromqtest-1/split_lib_slice_6_apk.apk", zip file "/data/app/com.futureskies.jeromqtest-1/split_lib_slice_7_apk.apk", zip file "/data/app/com.futureskies.jeromqtest-1/split_lib_slice_8_apk.apk", zip file "/data/app/com.futureskies.jeromqtest-1/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/vendor/lib64, /system/lib64]]
                                                                              at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                              at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                                              at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                                              at zmq.io.net.tcp.TcpListener.setAddress(TcpListener.java:186) 
                                                                              at zmq.SocketBase.bind(SocketBase.java:363) 
                                                                              at org.zeromq.ZMQ$Socket.bind(ZMQ.java:2333) `

**Comment by fredoboulo** [comment]
These are runtime errors, right? If so, that means that some others may be hidden...
but focusing on the current one, I now have a doubt if the server socket should be tuned like that...

@krumberg this is pretty the same for me

**Comment by skipe777** [comment]
Yes, there are runtime errors. Without going line by line through the source and checking against Android docs for available version info, I would agree that there could be more exceptions that haven't been reached yet.

**Comment by fredoboulo** [comment]
It's just painful to interact like that, as I do not have Android env at the moment. But that will happen, if you are not too much in hurry.

**Comment by Itaydal** [comment]
Hi @fredoboulo , any new with this issue?
I'll be really happy to start using encryption over my android app..

**Comment by fredoboulo** [comment]
Hi @Itaydal , changes were merged almost 2 weeks ago. I do not have Android environment (and there is no CI instance with it as well), so if you could give a try to the latest master, that would speed up the process.

**Comment by Itaydal** [comment]
@fredoboulo, How are you today?

looks like there are still some bad dependencies, one I ran into:

09-06 12:07:03.431 3138-3265/com.ore.zippo E/AndroidRuntime: FATAL EXCEPTION: network_sender_thread
                                                             java.lang.NoClassDefFoundError: java.util.Objects
                                                                 at zmq.poll.Poller$Handle.hashCode(Poller.java:41)
                                                                 at java.util.HashMap.put(HashMap.java:390)
                                                                 at java.util.HashSet.add(HashSet.java:95)
                                                                 at zmq.poll.Poller.addHandle(Poller.java:112)
                                                                 at zmq.Reaper.<init>(Reaper.java:40)
                                                                 at zmq.Ctx.initSlots(Ctx.java:421)
                                                                 at zmq.Ctx.createSocket(Ctx.java:365)
                                                                 at org.zeromq.ZMQ$Socket.<init>(ZMQ.java:432)
                                                                 at org.zeromq.ZMQ$Context.socket(ZMQ.java:356)
                                                                 at org.zeromq.ZContext.createSocket(ZContext.java:103)

A search for the unsupported import "java.util.Objects" over the entire repo gave:
[ValueReference](https://github.com/zeromq/jeromq/blob/bb0428c4d16d6c6045de303d9a43ad39239704d3/src/main/java/zmq/util/ValueReference.java#L3)
[Metadata](https://github.com/zeromq/jeromq/blob/15096f08983870d3f095bdf87b985768eff21bc4/src/main/java/zmq/io/Metadata.java#L3)
[Poller](https://github.com/zeromq/jeromq/blob/b92f615e395193c7395a9f37464bfe98270c0ada/src/main/java/zmq/poll/Poller.java#L12)
[PollerBase](https://github.com/zeromq/jeromq/blob/5b1a382467feee214eb9a713188a422bfceefc5d/src/main/java/zmq/poll/PollerBase.java#L4)


If you'll be able to fix all of those and merge to master I'll be happy to test for android again.

Thanks for the effort, I really appreciate it :)

**Comment by fredoboulo** [comment]
What is your minimum SDK version (API level target)?

**Comment by Itaydal** [comment]
android {
    compileSdkVersion 25
    buildToolsVersion "25.0.2"
    defaultConfig {
        minSdkVersion 17
        targetSdkVersion 25
...}
}

**Comment by fredoboulo** [comment]
I made a big move... @skipe777, @Itaydal please test it once it is merged.

**Comment by Aaronfoxh** [comment]
this is my configuration.
`android {
    compileSdkVersion 28
    defaultConfig {
        minSdkVersion 16
        targetSdkVersion 28
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        multiDexEnabled true
 }
}`

there are still some bad dependencies, one I ran into:
`java.lang.NoSuchMethodError: No static method stream([Ljava/lang/Object;)Ljava/util/stream/Stream; in class Ljava/util/Arrays; or its super classes (declaration of 'java.util.Arrays' appears in /system/framework/core-libart.jar)
`
run in android 5.1.1
