### ISSUE TITLE
PUB socket errors when connected to XSUB and all subscriptions are removed

### ISSUE THREAD

**Issue by rexfleischer** [zeromq/jeromq#476]
I've started using jeromq with 0.4.2, and i've been trying to implement a simple XPUB/XSUB broker. so i connect PUB sockets to the XSUB socket and SUB sockets to the XPUB socket. while making tests i found that the PUB sockets throw errors while attempting to send a publish if all subscriptions are removed. also note that when i bump the version back to 0.4.1, the error is thrown. but 0.4.0 does not throw this error. i have not tested if the error is thrown on the latest codebase, but the latest change to that line and file has been after 0.4.1 was bumped. (https://github.com/zeromq/jeromq/commit/a55462b5dba1a61f28f32500a551038b4f3269a2#diff-a0edbea7f5ccbdfb70c86352b10c7e2cL257)

here is the exception:
```
java.lang.ArrayIndexOutOfBoundsException: 6
	at zmq.socket.pubsub.Mtrie.rmHelper(Mtrie.java:254)
	at zmq.socket.pubsub.Mtrie.rm(Mtrie.java:238)
	at zmq.socket.pubsub.XPub.xreadActivated(XPub.java:104)
	at zmq.SocketBase.readActivated(SocketBase.java:1099)
	at zmq.pipe.Pipe.processActivateRead(Pipe.java:312)
	at zmq.ZObject.processCommand(ZObject.java:51)
	at zmq.Command.process(Command.java:75)
	at zmq.SocketBase.processCommands(SocketBase.java:937)
	at zmq.SocketBase.send(SocketBase.java:697)
	at org.zeromq.ZMQ$Socket.send(ZMQ.java:2443)
	at org.zeromq.ZFrame.send(ZFrame.java:131)
	at org.zeromq.ZFrame.sendAndKeep(ZFrame.java:146)
	at org.zeromq.ZMsg.send(ZMsg.java:182)
	at org.zeromq.ZMsg.send(ZMsg.java:154)
	at testing.BugShow.lambda$main$2(BugShow.java:41)
	at java.lang.Thread.run(Thread.java:748)
```

I'm very new to jeromq, and zeromq in general, so please let me know if i'm messing this up:
```
package testing;

import org.zeromq.ZContext;
import org.zeromq.ZMQ;
import org.zeromq.ZMsg;

import java.io.Closeable;

public class ShowIssueMaybe {
  public static void main(String[] args) throws Exception {
    ZContext broker_context = new ZContext();
    Thread broker = new Thread(() -> {
      ZMQ.Socket xpub = broker_context.createSocket(ZMQ.XPUB);
      xpub.bind("tcp://*:8881");
      ZMQ.Socket xsub = broker_context.createSocket(ZMQ.XSUB);
      xsub.bind("tcp://*:8882");
      ZMQ.proxy(xpub, xsub, null);
    });
    Thread subscriber = new Thread(() -> {
      ZContext context = new ZContext();
      ZMQ.Socket requester = context.createSocket(ZMQ.SUB);
      requester.connect("tcp://localhost:8881");
      requester.subscribe("hello".getBytes(ZMQ.CHARSET));
      int count = 0;
      while (count < 10) {
        ZMsg message = ZMsg.recvMsg(requester);
        System.out.println("[sub] " + thatsAPrettyZMsg(message));
        count++;
      }
      closeQuietly(context);
    });
    Thread publisher = new Thread(() -> {
      ZContext context = new ZContext();
      ZMQ.Socket pub = context.createSocket(ZMQ.PUB);
      pub.connect("tcp://localhost:8882");
      while (!Thread.currentThread().isInterrupted()) {
        try {
          ZMsg message = ZMsg.newStringMsg("hello", "world");
          System.out.println("[pub] " + thatsAPrettyZMsg(message));
          message.send(pub);
          Thread.sleep(250);
        }
        catch(Exception ex) {
          ex.printStackTrace();
          break;
        }
      }
      closeQuietly(context);
    });
    
    broker.start();
    subscriber.start();
    Thread.sleep(1000);
    publisher.start();
    subscriber.join();
    Thread.sleep(1000);
    
    System.out.println("publisher.interrupt()");
    publisher.interrupt();
    System.out.println("publisher.join()");
    publisher.join();
    System.out.println("broker_context.close()");
    broker_context.close();
  }

  private static String thatsAPrettyZMsg(ZMsg message) {
    return message.stream()
        .map(f -> new String(f.getData(), ZMQ.CHARSET))
        .reduce((l1, l2) -> l1 + ":" + l2).get();
  }
  
  private static void closeQuietly(Closeable closing) {
    try {
      closing.close();
    }
    catch(Exception ex) { /* empty */ }
  }
}
```

**Comment by fredoboulo** [comment]
No messing up from your side, this is definitely a bug... which means the mess up is from my side :/
Give me some time to investigate please.

**Comment by fredoboulo** [comment]
Thanks for reporting it!

**Comment by rexfleischer** [comment]
not a problem. the whole zeromq project is really great!
