### ISSUE TITLE
Polling a DEALER socket sometimes causes IndexOutOfBoundsException

### ISSUE THREAD

**Issue by daveyarwood** [zeromq/jeromq#488]
The context is that I'm writing a [Clojure JeroMQ wrapper library](https://github.com/daveyarwood/ezzmq) and translating the zguide examples as I go.

When I translated the multi-threaded server example (a single process with a ROUTER/DEALER proxy and 5 spawned worker threads running a REP server), ran it, and interrupted it via Ctrl-C, I found that the worker processes caught ETERM and exited successfully, but the server failed to shut down and blocked the process from exiting.

Occasionally, I got this stacktrace:

```
...
                                            ezzmq.poll/poll                     poll.clj:   71
                                            ezzmq.poll/poll                     poll.clj:   85
                                                        ...            
                                 org.zeromq.ZMQ$Poller.poll                     ZMQ.java: 2903
                                 org.zeromq.ZMQ$Poller.poll                     ZMQ.java: 2939
                                               zmq.ZMQ.poll                     ZMQ.java:  709
                                 zmq.poll.PollItem.readyOps                PollItem.java:  115
                                zmq.SocketBase.getSocketOpt              SocketBase.java:  257
                                      zmq.SocketBase.hasOut              SocketBase.java:  878
                           zmq.socket.reqrep.Dealer.xhasOut                  Dealer.java:   83
                                       zmq.socket.LB.hasOut                      LB.java:  135
                                    java.util.ArrayList.get               ArrayList.java:  429
                             java.util.ArrayList.rangeCheck               ArrayList.java:  653
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
         clojure.lang.ExceptionInfo: Index: 0, Size: 0
    line: 73
```

I traced it back to [this line in LB.java](https://github.com/zeromq/jeromq/blob/master/src/main/java/zmq/socket/LB.java#L135), which calls ArrayList.get on an index that is out of bounds. My guess is that the worker processes exited, so `pipes` is now of length 0, but we try to get `pipes[0]`.

I don't have much context on this part of the code, but I have two observations:

1. Is there a bug here?

2. If it's not a bug, since it's possible to get into this predicament, should we at least catch the exception and throw a more descriptive one? (or perhaps handle it more gracefully, like `return false` or something?)

**Comment by fredoboulo** [comment]
Difficult to say now and here without more infos, and I am not familiar with clojure, maybe someone else would provide better answers.

The usual (you know the drill)
- is there any chance that sockets are accessed by different threads?
- any minimalistic test code (in java) that reproduces the bug? which zguide example are you implementing exactly?

I would ask one favor: could you test it again with 0.3.6 or earlier? It would be useful to acknowledge if it is a regression due to the latest devs.

**Comment by daveyarwood** [comment]
I'm fairly certain that I'm not accessing sockets from multiple threads.

My Clojure code is a translation of [mtserver.java](https://github.com/zeromq/jeromq/blob/master/src/test/java/guide/mtserver.java):
  - The main thread binds ROUTER and DEALER sockets, polls them, and proxies requests between clients and workers.
  - 5 worker threads each connect to their own REP socket at the same inproc address -- the one the server is binding with the DEALER socket -- receive requests and send responses.

Each thread creates its own REP socket connected to `inproc://workers`, so I don't think this is an issue where the same socket is accessed by multiple threads.

When I have some time, I'll see if I can put together some Java code that will reproduce the issue. One thing I'm doing that's probably different from the tests we have is that I'm not using the `proxy` convenience function, but polling the sockets manually. In theory that's all the proxy is supposed to be doing, but I'm wondering if there is some extra magic that I'm not including when I do it manually.

**Comment by fredoboulo** [comment]
The fact that you use it differently may be in cause, I played a bit with mtserver, closing REPs and recreating them several times did not create any abnormal behaviour with proxy.
Another cause may be that the SIGINT is not properly handled (as you are using Ctrl+C), but it would be difficult to create a proper test for that.

**Comment by daveyarwood** [comment]
Oh yeah, good point. I'll probably just make a quick Java sample project that demonstrates the issue.

**Comment by daveyarwood** [comment]
I'm working on reproducing the issue in Java. So far no luck, but I did find one area of concern in the code:

https://github.com/zeromq/jeromq/blob/v0.4.2/src/main/java/zmq/socket/FQ.java#L59-L70:

```java
        final int index = pipes.indexOf(pipe);

        //  Remove the pipe from the list; adjust number of active pipes
        //  accordingly.
        if (index < active) {
            active--;
            Collections.swap(pipes, index, active);
            if (current == active) {
                current = 0;
            }
        }
        pipes.remove(pipe);
```

Based on the stacktrace I'm seeing (`java.lang.ArrayIndexOutOfBoundsException: -1`), it's possible for `pipes.indexOf(pipe)` to return -1. I have a theory that this could be happening because the same pipe is terminated more than once for some reason. Regardless, I think we need to code against the possibility that `index` ends up being -1, so that it doesn't trigger an uncaught exception.

I'll keep digging, but thought I'd share what I found so far.

**Comment by daveyarwood** [comment]
Alright -- I've reproduced the issue by writing some Java code.

The code is here: https://github.com/daveyarwood/jeromq-mtserver-example

There is a fair amount to unpack here -- I'm doing things a bit differently from the example code in the zguide, based on my experience with / understanding of JeroMQ. 

To make what I'm doing easier to understand, I jotted down the differences in the README.

**Comment by daveyarwood** [comment]
I'm curious if this is related? https://github.com/zeromq/jeromq/wiki/Sharing-ZContext-between-thread

I never understood why a ZContext can't be shared between e.g. main thread and worker threads. Is ZContext not considered thread-safe, and if so, why? 

If in fact a ZContext should not be shared with a worker thread, then that could perhaps be related to the exceptions I'm seeing.

**Comment by fredoboulo** [comment]
Hello Dave, considering FQ, it would make sense for me. Root of the problem seem to be in another yet unidentified level, but that would not harm to introduce something like
```
if (index < 0) {
  return;
}
```

I tried your code, I do not see obvious misuse of the lib, and on ubuntu 16.04 and java 1.8.0_131, kill -s INT <pid> does not do anything, meaning it does not stop the running program...

ZContext#createPoller is present in 0.4.0, if you could try with that version, that could at least assess if it is a new problem introduced recently.

**Comment by daveyarwood** [comment]
After running my example on 0.4.0 successfully about 10 times (mostly successfully, except for 1 time when the process hung), I ran into what might be a similar issue:

```
$ boot run
Compiling 1 Java source files...
Binding frontend DEALER socket on port 36847...
Binding backend ROUTER socket at inproc://workers...
Starting workers...
[worker 0] Reporting for duty!
[worker 1] Reporting for duty!
[worker 2] Reporting for duty!
[worker 3] Reporting for duty!
Proxying requests...
[worker 4] Reporting for duty!
^CShutting down.
Exception in thread "reaper-1" java.lang.IndexOutOfBoundsException: Index: 4, Size: 2
        at java.util.ArrayList.rangeCheck(ArrayList.java:653)
        at java.util.ArrayList.get(ArrayList.java:429)
        at zmq.SocketBase.processTerm(SocketBase.java:851)
        at zmq.Own.terminate(Own.java:172)
        at zmq.SocketBase.startReaping(SocketBase.java:764)
        at zmq.Reaper.processReap(Reaper.java:121)
        at zmq.ZObject.processCommand(ZObject.java:94)
        at zmq.Reaper.inEvent(Reaper.java:76)
        at zmq.Poller.run(Poller.java:228)
        at java.lang.Thread.run(Thread.java:745)
```

The references line in SocketBase is here: https://github.com/zeromq/jeromq/blob/v0.4.0/src/main/java/zmq/SocketBase.java#L851

**Comment by fredoboulo** [comment]
All of that seems like an old pandora box for me, some reminder of long lasting problems that I saw when I first tried the lib for my projects.
I have no golden bullet for that, I can always propose some of my works on closing/terminating process, but  before doing so I would wait for a next release (a stable one) and the outcome of a big question mark for me: do we strictly follow the basecode present on libzmq, or is there any room to propose some variation to the canon code?

**Comment by daveyarwood** [comment]
Action needed on my part: test with JeroMQ 0.4.3 (or perhaps 0.5.0 once it's out) and see if the issue is still reproducible.

**Comment by daveyarwood** [comment]
Tested my repro example with JeroMQ 0.4.3; the problem persists. Across a large handful of runs, a few of them produced results like before (process hangs; ArrayIndexOutOfBoundsException), and one of them produced something new, a ClosedChannelException.

**Comment by daveyarwood** [comment]
My repro example is a repo that I linked above [here](https://github.com/zeromq/jeromq/issues/488#issuecomment-334341814). If you have [Boot](https://boot-clj.com) installed, you can just check out that repo and run `boot run` to repro. As noted in the README, you may need to run it several times to get it to repro, and it tends to manifest in several different ways (IndexOutOfBoundException, ClosedChannelException, ArrayIndexOutOfBoundException, process hangs, etc.)

**Comment by trevorbernard** [comment]
The shutdown hook runs in a separate thread which is incorrect use. I guess the problem we should be solving is trying to eliminate the process hang when the context is closed down incorrectly

**Comment by daveyarwood** [comment]
Interesting -- that hadn't occurred to me!

So is [what we're doing in the "interrupt" example](https://github.com/zeromq/jeromq/blob/3ac3c32/src/test/java/guide/interrupt.java#L45-L59) not advisable? Is there a better way to take care of cleaning up / shutting things down if the program I'm writing is interrupted?

I still think that we could code around the two "index out of bounds" exceptions, as I described above [here](https://github.com/zeromq/jeromq/issues/488#issue-261683429) and [here](https://github.com/zeromq/jeromq/issues/488#issuecomment-334041177). The fact that we even make it possible for an "index out of bounds" exception to occur feels like unsafe coding to me. There has to be a safer way to do what we're trying to do in those parts of the codebase.
