### ISSUE TITLE
NPE 'void zmq.Mailbox.send(zmq.Command)'

### ISSUE THREAD

**Issue by madrzak** [zeromq/jeromq#518]
Hello again gents,

We are getting the following Null Pointer Exception. 

Using the latest version 4.3 on Android. Can be replicated consistently enough after enabling/disabling Airplane mode on the device couple of times. 

Any thoughts? 

02-05 15:37:40.090 W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'void zmq.Mailbox.send(zmq.Command)' on a null object reference
02-05 15:37:40.090 W/System.err:     at zmq.Ctx.sendCommand(Ctx.java:517)
02-05 15:37:40.091 W/System.err:     at zmq.ZObject.sendCommand(ZObject.java:382)
02-05 15:37:40.091 W/System.err:     at zmq.ZObject.sendTermAck(ZObject.java:270)
02-05 15:37:40.091 W/System.err:     at zmq.Own.checkTermAcks(Own.java:250)
02-05 15:37:40.091 W/System.err:     at zmq.Own.processSeqnum(Own.java:105)
02-05 15:37:40.091 W/System.err:     at zmq.ZObject.processCommand(ZObject.java:74)
02-05 15:37:40.091 W/System.err:     at zmq.Command.process(Command.java:75)
02-05 15:37:40.091 W/System.err:     at zmq.io.IOThread.inEvent(IOThread.java:80)
02-05 15:37:40.091 W/System.err:     at zmq.poll.Poller.run(Poller.java:273)
02-05 15:37:40.092 W/System.err:     at java.lang.Thread.run(Thread.java:762)

**Comment by fredoboulo** [comment]
Hi,

NPE at this precise location would mean that a mailbox has been destroyed.
I would suspect either:
- socket has been closed
- IO thread or reaper has been destroyed.

Could you provide some code around that error to explain your usage? where, when and how does this code destroys sockets and context?
