### ISSUE TITLE
Issue #520 still occuring

### ISSUE THREAD

**Issue by chinababu** [zeromq/jeromq#531]
I am still getting this error continuously even with #520 fix. 
Particularly I am getting this error when beginPos == size (when size=256). 

java.lang.NullPointerException
	at zmq.pipe.YQueue.frontPos(YQueue.java:63)
	at zmq.pipe.YPipe.checkRead(YPipe.java:102)
	at zmq.pipe.YPipe.read(YPipe.java:137)
	at zmq.pipe.Pipe.read(Pipe.java:214)
	at zmq.io.SessionBase.pullMsg(SessionBase.java:126)
	at zmq.io.StreamEngine$PullAndEncode.nextMsg(StreamEngine.java:117)
	at zmq.io.StreamEngine.outEvent(StreamEngine.java:555)
	at zmq.io.IOObject.outEvent(IOObject.java:92)
	at zmq.poll.Poller.run(Poller.java:270)
	at java.lang.Thread.run(Thread.java:745)

I added this log to YQueue.pop() method.
pop:therad id: 12:iothread-2:RUNNABLE:  beginChunk.values:[Ljava.lang.Object;@450982e1, beginPos:256, size:256
beginChunk.next is null.
I do not know much internal details of JeroMQ. I did not yet come to any conclusion why beginPos is reaching to 256. 
Note: we have haproxy before zeromq. So, all traffic goes thru haproxy. not sure if that is the reason.
Can you suggest some steps to narrow down?

Environment:
 OS: 3.10.0-514.36.5.el7.x86_64 GNU/Linux
 JeroMQ 0.4.2
 openjdk version "1.8.0_102"
 OpenJDK Runtime Environment (build 1.8.0_102-b14)
 OpenJDK 64-Bit Server VM (build 25.102-b14, mixed mode)

Thanks,
Chinna

**Comment by fredoboulo** [comment]
This seems to be related to #516 rather than #520:
#516 is about NPE in YQueue, #520 is about infinite loop in IO-thread.

If so, please close this issue and continue the topic on #516.
