### ISSUE TITLE
java.lang.NullPointerException at zmq.pipe.Pipe.isDelimiter that turns JeroMQ into non-working state 

### ISSUE THREAD

**Issue by vsiryi** [zeromq/jeromq#558]
Original issue happened several times on production where we use JeroMQ. The problem was manifested in the fact that all clients disconnected from the server simultaneously without possibility to re-connect again till server restart.

Exception: 
`Exception in thread "pool-2-thread-1" java.lang.NullPointerException
	at zmq.pipe.Pipe.isDelimiter(Pipe.java:504)
	at zmq.pipe.Pipe.checkRead(Pipe.java:193)
	at zmq.socket.FQ.hasIn(FQ.java:146)
	at zmq.socket.pipeline.Pull.xhasIn(Pull.java:52)
	at zmq.SocketBase.hasIn(SocketBase.java:872)
	at zmq.SocketBase.getSocketOpt(SocketBase.java:260)
	at zmq.poll.PollItem.readyOps(PollItem.java:121)
	at zmq.ZMQ.poll(ZMQ.java:724)
	at org.zeromq.ZMQ$Poller.poll(ZMQ.java:3832)
	at net.overc.zmq.server.BiDirectionMessageServer.lambda$0(BiDirectionMessageServer.java:78)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)`

I have prepared 'as small as possible' project for reproduce issue: https://github.com/vsiryi/zmq-fatal-error

- Server implemented as ROUTER socket and may possibility to track online users (heartbeat), map connection identity with user id and send some messages (events) to a specific user.
- Client implemented as DEALER socket. In example it make 'pong' response message based on 'ping' message from server and read 'event' message.

Please execute net.overc.zmq.ReproduceFatalException.reproduce for reproduce an exception. This test run a server and than run 15 clients. Please note that issue reproduced time by time. Usually enough to do 3-4 executions for reproduce.

After this exception all existing connections will be disconnected (receive ZMonitor.Event.DISCONNECTED events). New connections from clients will be accepted but also disconnected in few seconds.  

Catch an exception in production code doesn't help because all next org.zeromq.ZMQ$Poller.poll invocations produce same exception.

**Comment by fredoboulo** [comment]
Hello, that looks like a fait amount of code. I do not have much time now for investigation, but I can already say that it may happen if your sockets are shared between threads, which seems to be the case. It means that send(), receive() and close() methods calls have to be performed inside the same thread.

**Comment by trevorbernard** [comment]
I spoke with @vsiryi and have confirmed it was a multithreading issue in the client application and not an issue with JeroMQ.
