### ISSUE TITLE
PollTest fails when all tests, but not individual tests

### ISSUE THREAD

**Issue by Alex-Mann** [zeromq/jeromq#637]
When running `mvn test -Dtest=PollTest` the test class fails and the error is:
```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running zmq.PollTest
Tests run: 3, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.095 sec <<< FAILURE!
testPollUdp(zmq.PollTest)  Time elapsed: 0.009 sec  <<< FAILURE!
java.lang.AssertionError:
Expected: is <2>
     but: was <3>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:865)
	at org.junit.Assert.assertThat(Assert.java:832)
	at zmq.PollTest.testPollUdp(PollTest.java:208)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)


Results :

Failed tests:   testPollUdp(zmq.PollTest): (..)

Tests run: 3, Failures: 1, Errors: 0, Skipped: 0
```

However, running all test cases individually is ok. Test cases are run individually like so:
`mvn test -Dtest=PollTest#testPollUdp`

with output:
```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running zmq.PollTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.088 sec

Results :

Tests run: 1, Failures: 0, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  5.827 s
[INFO] Finished at: 2019-01-26T16:43:12-05:00
[INFO] ------------------------------------------------------------------------
```

**Comment by fredoboulo** [comment]
Does it happen with the latest master? On my machine, with commit 7d53a81, the test passes, individually, when running PollTest and when running all tests.

> java -version
> openjdk version "10.0.2" 2018-07-17
> OpenJDK Runtime Environment (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.4)
> OpenJDK 64-Bit Server VM (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.4, mixed mode)

**Comment by Alex-Mann** [comment]
Hm, could be related to my JDK then? I'm on a Mac with
```
➜  jeromq git:(master) java -version
java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)
```
Can also confirm that I am using the latest master.

**Comment by trevorbernard** [comment]
I've found the poll tests to be a bit problematic but I haven't had time to debug it any more than 5-10 mins.

**Comment by fredoboulo** [comment]
I totally trust you on your findings, but it's passing all the time for me, so I'm kinda stuck here.

**Comment by fredoboulo** [comment]
I needed to repeat the tests around 5 million times (!) to trigger problems, but I found a possible solution on my machine.
