### ISSUE TITLE
Errno 48 publish-subscribe with a specific IP address

### ISSUE THREAD

**Issue by smaillns** [zeromq/jeromq#739]
```java
public class Publisher {

        public static void main(String[] args) throws Exception
        {
            //  Prepare our context and Publisher
            try (ZContext context = new ZContext()) {
                ZMQ.Socket publisher = context.createSocket(SocketType.PUB);
                publisher.bind("tcp://140.93.0.95:5678");


            int id = 1;
            String msg = "";
            while (true){
                Thread.sleep(1000);

                msg = "topic1- msg"+id ;
                publisher.send(msg);

                id++;

            }

            }
        }
    }
```

When using  ZMQ Pub-Sub  pattern with an external IP address I get the following error

> Exception in thread "main" org.zeromq.ZMQException: Errno 48 : Address already in use
	at org.zeromq.ZMQ$Socket.mayRaise(ZMQ.java:3533)
	at org.zeromq.ZMQ$Socket.bind(ZMQ.java:2987)
	at com.zmq.pub_sub.Publisher.main(Publisher.java:16) 

PS : I want to use ZMQ between two remote machines

**Comment by trevorbernard** [comment]
It's probably the case that IP address:port is actually in use. Check that another process isn't listening on that same port.

**Comment by daveyarwood** [comment]
Closing due to inactivity. Feel free to reopen if needed.
