### ISSUE TITLE
Exception in combination with docker

### ISSUE THREAD

**Issue by chrizzly123** [zeromq/jeromq#754]
Hey guys,

I have a setup where i want to run a server application with a Pub Socket inside a Docker container, there are some client applications with a Sub Socket connecting to the server application.
Although, on running sub.recv(), I get the following NullPointerException on the client Application:
```java
java.lang.NullPointerException
	at zmq.pipe.Pipe.isDelimiter(Pipe.java:504)
	at zmq.pipe.Pipe.checkRead(Pipe.java:193)
	at zmq.io.SessionBase.readActivated(SessionBase.java:255)
	at zmq.pipe.Pipe.processActivateRead(Pipe.java:312)
	at zmq.ZObject.processCommand(ZObject.java:51)
	at zmq.Command.process(Command.java:75)
	at zmq.io.IOThread.inEvent(IOThread.java:80)
	at zmq.poll.Poller.run(Poller.java:273)
	at java.base/java.lang.Thread.run(Thread.java:830)
```

Here is a repo with code and steps to reproduce: [https://github.com/chrizzly123/jeromq_docker_issue](https://github.com/chrizzly123/jeromq_docker_issue)

Probably related: [https://github.com/zeromq/jeromq/issues/516](https://github.com/zeromq/jeromq/issues/516)

Running on another machine showed the same results.
If the server application is running without Docker, everything works fine. 

Thanks!
Chris

```java
public class Server {

  public static void main(String[] args) throws InterruptedException {
    System.out.println("setting up");
    Thread.sleep(1000);

    ZContext context = new ZContext();
    Thread.sleep(1000);

    Socket pub = context.createSocket(SocketType.PUB);
    Thread.sleep(1000);

    System.out.println("binding: " + pub.bind("tcp://127.0.0.1:10000"));
    Thread.sleep(1000);

    System.out.println("now ready...");
    Thread.currentThread().join(); //sleep
  }
}
```

```java
public class Client {

  public static void main(String[] args) throws InterruptedException {
    System.out.println("setting up");
    Thread.sleep(1000);

    ZContext context = new ZContext();
    Thread.sleep(1000);

    Socket sub = context.createSocket(SocketType.SUB);
    Thread.sleep(1000);

    System.out.println("connected: " + sub.connect("tcp://127.0.0.1:10000"));
    Thread.sleep(1000);

    System.out.println("subscribed: " + sub.subscribe("server"));
    Thread.sleep(1000);

    System.out.println("now trying to receive, which will throw the exception:");
    sub.recv();
  }
}
```

**Comment by nalim2** [comment]
The mentioned issue #516  suggest to change the zmq.pipe.class function isDelimiter(Msg msg) from:
```java
private static boolean isDelimiter(Msg msg) {
        return msg.isDelimiter();
 }
```
to:
```java
private static boolean isDelimiter(Msg msg)
    {
        return (msg != null && msg.isDelimiter());
    }
```
This fixes this problem in this particular case and leads through the test suite with the same results as the actual master industry on a Windows 10 AMD64/x86 system. But is this then the correct behavior for the separator in Jeromq?

**Comment by fredoboulo** [comment]
Hi,

Try to modify your Server code to continuously send messages (pub.send("server-blablabla")).
Normally the Client should finally receive one and end.

I tried on  my machine (with modified isDelimiter method) and it won't.
However, when I modified the Server code to bind to all (pub.bind("tcp://*:10000"), it worked.

Seems like the engine endlessly errors while handshaking, which triggers hiccup on the pipe, and at some point the pipes are not in sync anymore. I wonder if a libzmq client would suffer the same fate.
