### ISSUE TITLE
Attempt to invoke virtual method 'void java.nio.channels.ServerSocketChannel.close()' on a null object reference

### ISSUE THREAD

**Issue by OzErDincKan** [zeromq/jeromq#773]
Hello there,
I would like to use JeroMQ in android application. I found a sample code in Kotlin, I tried it. It works in android studio. I put same code in a android application. When I tried to run, I have NullPointerException error. When I checked the line, the line is `ZMQ.context(1)`. 
I searched your Issues page and googled but I could not find any solution for that. 
You could find my code parts and error message below.
JeroMQ version is `org.zeromq:jeromq:0.5.2`
Could you help me?

`class MainActivity : AppCompatActivity() {

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)
        findViewById<Button>(R.id.button).setOnClickListener {
            findViewById<TextView>(R.id.text).setText("hello ozkan");

            val serverPort = 5898;
            val context = ZMQ.context(1)

            val socket = context.socket(SocketType.REP)
            println("Starting the server($serverPort)...")
            socket.bind("tcp://*:$serverPort")

            while (true) {
                val rawRequest = socket.recv(0)
                val cleanRequest = String(rawRequest, 0, rawRequest.size - 1)
                println("Request received : $cleanRequest")
                var plainReply = "World "
                var rawReply = plainReply.toByteArray()
                rawReply[rawReply.size - 1] = 0
                socket.send(rawReply, 0)
            }
        }
    }
}`

> 2020-04-13 02:30:06.352 17308-17308/? D/AndroidRuntime: Shutting down VM
2020-04-13 02:30:06.353 17308-17308/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.myapplication, PID: 17308
    java.lang.NullPointerException: Attempt to invoke virtual method 'void java.nio.channels.ServerSocketChannel.close()' on a null object reference
        at zmq.io.net.tcp.TcpListener.close(TcpListener.java:141)
        at zmq.io.net.tcp.TcpListener.setAddress(TcpListener.java:205)
        at zmq.SocketBase.bind(SocketBase.java:367)
        at org.zeromq.ZMQ$Socket.bind(ZMQ.java:2999)
        at com.example.myapplication.MainActivity$onCreate$1.onClick(MainActivity.kt:23)
        at android.view.View.performClick(View.java:7161)
        at android.view.View.performClickInternal(View.java:7138)
        at android.view.View.access$3500(View.java:811)
        at android.view.View$PerformClick.run(View.java:27419)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:7520)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
2020-04-13 02:30:06.356 17308-17308/? E/MQSEventManagerDelegate: failed to get MQSService.
2020-04-13 02:30:06.368 17308-17308/? I/Process: Sending signal. PID: 17308 SIG: 9
>

**Comment by daveyarwood** [comment]
I'm not sure off-hand what the problem is, but the first thing I would try is to use ZContext instead of ZMQ.context. ZMQ.context is a lower-level implementation detail and should not be used when using JeroMQ in your application.

For more information about contexts in JeroMQ: https://github.com/zeromq/jeromq/blob/master/doc/contexts.md

**Comment by OzErDincKan** [comment]
Dear Dave,
Thank you so much for your fast response.
I applied your proposal on my code. New lines below. When I tried it, I had same problem on `socket.bind` line. 
You could find my code and error messages below.
Do you have any other proposal for me?

`       view.findViewById<Button>(R.id.bStartServer).setOnClickListener {

            val serverPort = 5898;
            val context = ZContext(1)
            val socket = context.createSocket(SocketType.REP);
            println("Starting the server($serverPort)...")
            view.findViewById<TextView>(R.id.editText).append("Starting the server($serverPort)...\n")

            socket.bind("tcp://*:$serverPort")

             while (true) {
                //recv takes an argument telling us whether the socket should block or not
                val rawRequest = socket.recv(0)
                //messages sent on zeromq are zero terminated. In our case we'll be using a string and we'll omit this last zero by ommiting the last byte from the request
                val cleanRequest = String(rawRequest, 0, rawRequest.size - 1)
                println("Request received : $cleanRequest")
                var plainReply = "World "
                var rawReply = plainReply.toByteArray()
                //we then set the last byte of the reply to 0
                rawReply[rawReply.size - 1] = 0
                socket.send(rawReply, 0)
            }
        }`

> 2020-04-13 21:28:58.861 7032-7032/com.example.serverandclientide E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.serverandclientide, PID: 7032
    java.lang.NullPointerException: Attempt to invoke virtual method 'void java.nio.channels.spi.AbstractInterruptibleChannel.close()' on a null object reference
        at zmq.io.net.tcp.TcpListener.close(TcpListener.java:141)
        at zmq.io.net.tcp.TcpListener.setAddress(TcpListener.java:205)
        at zmq.SocketBase.bind(SocketBase.java:367)
        at org.zeromq.ZMQ$Socket.bind(ZMQ.java:2999)
        at com.example.serverandclientide.FirstFragment$onViewCreated$2.onClick(FirstFragment.kt:42)
        at android.view.View.performClick(View.java:5637)
        at android.view.View$PerformClick.run(View.java:22429)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6119)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by OzErDincKan** [comment]
Hello there,
I would like share about my last state. I solved the problem. The reason is android's internet permissions. I had some permissions to access network but I understood that it was not enough. After I put `<uses-permission android:name="android.permission.INTERNET" />`, it is running very well. My permissions are now;
`    <uses-permission
        android:name="android.permission.ACCESS_NETWORK_STATE"
        android:required="true" />
    <uses-permission
        android:name="android.permission.ACCESS_WIFI_STATE"
        android:required="true" />
    <uses-permission
        android:name="android.permission.INTERNET"
        android:required="true" />`

I am closing the issue.
Thank you so much.
