### ISSUE TITLE
org.zeromq.ZMQException: Errno 156384819 : errno 156384819

### ISSUE THREAD

**Issue by marlonli** [zeromq/jeromq#799]
We are using version 0.5.1
Some of our applications got the following error:
org.zeromq.ZMQException: Errno 156384819 : errno 156384819
	at zmq.Ctx.createSocket(Ctx.java:398)
	at org.zeromq.ZMQ$Socket.<init>(ZMQ.java:833)
	at org.zeromq.ZMQ$Socket.<init>(ZMQ.java:819)
	at org.zeromq.ZMQ$Context.socket(ZMQ.java:652)
	at org.zeromq.ZContext.createSocket(ZContext.java:131)
	at org.zeromq.ZContext.createSocket(ZContext.java:148)

The error 156384819 is caused by no empty slot available. The maxSlotCount is 1024 by default, is there any way to increase this maxSlotCount?

**Comment by marlonli** [comment]
Just found ZMQ.setMaxSockets()
