### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by zhongfuqiang** [zeromq/jeromq#871]
java.lang.NullPointerException
	at zmq.io.StreamEngine.restartInput(StreamEngine.java:557)
	at zmq.io.SessionBase.writeActivated(SessionBase.java:276)
	at zmq.pipe.Pipe.processActivateWrite(Pipe.java:324)
	at zmq.ZObject.processCommand(ZObject.java:55)
	at zmq.Command.process(Command.java:75)
	at zmq.io.IOThread.inEvent(IOThread.java:80)
	at zmq.poll.Poller.run(Poller.java:273)
	at java.lang.Thread.run(Thread.java:748)

**Comment by fbacchella** [comment]
Can you reproduce it ? Can you run your code with -ea to enable assertions ?
