### ISSUE TITLE
Native image build failures on latest GraalVM with Random/SplittableRandom initialized at build time

### ISSUE THREAD

**Issue by sriharsha-github** [zeromq/jeromq#893]
I am using jeromq version `0.5.2` with [quarkus](https://quarkus.io), when I try to build a native image it throws an error:

```
Error: No instances of sun.security.provider.NativePRNG are allowed in the image heap as this class should be initialized at image runtime. To see how this object got instantiated use --trace-object-instantiation=sun.security.provider.NativePRNG.
Detailed message:
Trace: Object was reached by
        reading field java.security.SecureRandom.secureRandomSpi of
                constant java.security.SecureRandom@18595b91 reached by
        scanning method zmq.util.Utils.randomInt(Utils.java:27)
Call path from entry point to zmq.util.Utils.randomInt():
        at zmq.util.Utils.randomInt(Utils.java:27)
        at zmq.io.net.tcp.TcpConnecter.getNewReconnectIvl(TcpConnecter.java:227)
        at zmq.io.net.tcp.TcpConnecter.addReconnectTimer(TcpConnecter.java:203)
        at zmq.io.net.tcp.TcpConnecter.connectEvent(TcpConnecter.java:122)
        at zmq.poll.Poller.run(Poller.java:267)
        at java.lang.Thread.run(Thread.java:829)
        at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:519)
        at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
        at com.oracle.svm.core.code.IsolateEnterStub.PosixJavaThreads_pthreadStartRoutine_e1f4a8c0039f8337338252cd8734f63a79b5e3df(generated:0)
```
In the upcoming release of GraalVM (21.1) instances of Random/SplittableRandom class won't be allowed in the native image heap. The corresponding patch can be seen [here](https://github.com/oracle/graal/commit/11b9817fb341f9447c300304fe461933bf79c2aa#diff-8ea159555f76609d835155ca3b7f534b8a5adbb932fa6366c4db09a5b2ec2275R62).

It would be great if jeromq can initialize `java.security.SecureRandom` at runtime rather than at build time.

**Comment by fbacchella** [comment]
You should have a look at this page: https://tersesystems.com/blog/2015/12/17/the-right-way-to-use-securerandom/.
It might help you.

**Comment by fbacchella** [comment]
The associated pull request was closed, with the following work around:
```
quarkus.native.additional-build-args=--initialize-at-run-time=zmq.util.Utils
```

So closing the issue too.
