### ISSUE TITLE
periodic index-out-of-bounds error

### ISSUE THREAD

**Issue by stealthrabbi** [zeromq/jeromq#938]
Using v0.5.2

My program is able to run days sending binary pictures, but will occasionally encounter an IndexOutOfBoundsException. I am not sure if it's an apparent issue with the data being sent to the zmq client, or something with a connection. The issue is not easily repeatable.

Also, are there release notes for different versions? I see there's now a 0.5.3, but I can't tell what's been added to it.

```
Exception in thread "My Thread" Exception in thread "My Thread" java.lang.IndexOutOfBoundsException: Index 1 out of bounds for length 1
        at java.base/jdk.internal.util.Preconditions.outOfBounds(Unknown Source)
        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Unknown Source)
        at java.base/jdk.internal.util.Preconditions.checkIndex(Unknown Source)
        at java.base/java.util.Objects.checkIndex(Unknown Source)
        at java.base/java.util.ArrayList.get(Unknown Source)
        at zmq.socket.pubsub.Dist.distribute(Dist.java:162)
        at zmq.socket.pubsub.Dist.sendToMatching(Dist.java:138)
        at zmq.socket.pubsub.XPub.xsend(XPub.java:253)
        at zmq.SocketBase.send(SocketBase.java:718)
        at org.zeromq.ZMQ$Socket.send(ZMQ.java:3205)
        at org.zeromq.ZFrame.send(ZFrame.java:136)
        at org.zeromq.ZFrame.sendAndKeep(ZFrame.java:151)
        at org.zeromq.ZMsg.send(ZMsg.java:187)
        at org.zeromq.ZMsg.send(ZMsg.java:159)
        at org.zeromq.proto.ZPicture.sendBinaryPicture(ZPicture.java:168)
        at org.zeromq.ZMQ$Socket.sendBinaryPicture(ZMQ.java:3342)
		<<my code>>

```

**Comment by stealthrabbi** [comment]
@trevorbernard I will try. The issue is that the exception sometimes takes many days to surface. Do you happen to have a list of things changed in 0.5.2 -> 0.5.3

**Comment by trevorbernard** [comment]
https://github.com/zeromq/jeromq/blob/master/CHANGELOG.md

**Comment by stealthrabbi** [comment]
No the issue still exists. Took about 24 hours to recreate. In my program, I've added an exception handler for this case, but I see now that the exception continues forever. I am guessing I need to create a new zmq socket

**Comment by fbacchella** [comment]
Just to be sure, the XPub socket is not shared between threads ?

**Comment by fbacchella** [comment]
Can you try with this branch: https://github.com/fbacchella/jeromq/tree/issue938 ?

**Comment by elihusmails** [comment]
I am still seeing this issue with version 0.5.4.

**Comment by elihusmails** [comment]
I added the changes to the Dist.java in my local 0.5.4 environment and recompiled/installed the change.  While I'm not getting the stack trace, it appears that my app is silently failing now.  I'm going to dig into this more.
