### ISSUE TITLE
MsgsendBlockAndCpuIs100%

### ISSUE THREAD

**Issue by jqwyy** [zeromq/jeromq#946]
"task-puller-pool-1" #156 prio=5 os_prio=0 tid=0x00007f73c5597800 nid=0x3f563c runnable [0x00007f72d35fa000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.FileDispatcherImpl.read(FileDispatcherImpl.java:46)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:197)
	at sun.nio.ch.SourceChannelImpl.read(SourceChannelImpl.java:167)
	- locked <0x00000006d81ef018> (a java.lang.Object)
	at zmq.Signaler.recv(Signaler.java:159)
	at zmq.Mailbox.recv(Mailbox.java:97)
	at zmq.SocketBase.processCommands(SocketBase.java:931)
	at zmq.SocketBase.send(SocketBase.java:696)
	at org.zeromq.ZMQ$Socket.send(ZMQ.java:2588)
	at org.zeromq.ZFrame.send(ZFrame.java:138)
	at org.zeromq.ZFrame.sendAndKeep(ZFrame.java:153)
	at org.zeromq.ZMsg.send(ZMsg.java:182)

when msg is sending,thread running and cpu is 100%.
![image](https://user-images.githubusercontent.com/124542734/216872622-a0a2c105-7825-4a1f-95ad-779c55f259d0.png)

**Comment by jqwyy** [comment]
note the version of jeromq is 0.4.3

**Comment by fbacchella** [comment]
The current version is 0.5.3, irrelevant.

**Comment by jqwyy** [comment]
yeah,I have no idea whether this problem has resovled after version 0.4.3 ,see the submits,has not find something relevant

**Comment by fbacchella** [comment]
Test with latest version, try to investigate, and reproduce it. Then come back with an usable ticket.

**Comment by jqwyy** [comment]
not throws any exceptions,I want to understand reason

**Comment by jqwyy** [comment]
ok,I try it ,3Q

**Comment by cankill** [comment]
Under the high load the Router socket hangs after some time in the Signaler recv(). 'nbytes == 0' true for infinity time.
Either on send or on receive or on poll or on getting events of the socket.
Does anyone have any clue what is going on?
Mac os X Ventura (Version 13.2.1 (22D68)). Java (18.0.1-oracle).
