### ISSUE TITLE
reaper-1 thread consuming 99.9% CPU

### ISSUE THREAD

**Issue by nethibernate** [zeromq/jeromq#956]
While using the jeromq library, we suddenly encountered an issue where the reaper-1 thread is consuming 99.9% CPU. The issue occurred unexpectedly, as it hadn't happened during previous runs. The stack trace of the reaper-1 thread is as follows:
```
"reaper-1" #35 daemon prio=5 os_prio=0 cpu=66154861.28ms elapsed=98947.99s tid=0x00007fe494583d10 nid=0x3d runnable  [0x00007fe4bd1ce000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.FileDispatcherImpl.read0(java.base@17.0.3/Native Method)
	at sun.nio.ch.FileDispatcherImpl.read(java.base@17.0.3/FileDispatcherImpl.java:48)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(java.base@17.0.3/IOUtil.java:330)
	at sun.nio.ch.IOUtil.read(java.base@17.0.3/IOUtil.java:296)
	at sun.nio.ch.IOUtil.read(java.base@17.0.3/IOUtil.java:259)
	at sun.nio.ch.SourceChannelImpl.read(java.base@17.0.3/SourceChannelImpl.java:277)
	at zmq.Signaler.recv(Signaler.java:165)
	at zmq.Mailbox.recv(Mailbox.java:97)
	at zmq.SocketBase.processCommands(SocketBase.java:937)
	at zmq.SocketBase.inEvent(SocketBase.java:1065)
	at zmq.poll.Poller.run(Poller.java:273)
	at java.lang.Thread.run(java.base@17.0.3/Thread.java:833)
```
Our server environment is as follows:

- OS: CentOS 7
- Java: 17.0.3
- jeromq: 0.5.2

Could you please help us investigate this issue and provide any possible solutions? Thank you in advance!

**Comment by fbacchella** [comment]
Current release is 0.5.3, try it.

**Comment by gaofei1982** [comment]
see: https://github.com/zeromq/jeromq/issues/859
